lib/minimist.js, test/parse.js
`yargs.config("c").describe("c", "Config file path").default("c","config.json")` will now work as expected.
We should probably make this a `2.x.x` release, because it changes the order of `['baz', 'bar']` to `['bar', 'baz']` (in reality, this shouldn't effect anyone unless they're writing really wonky code).
=> make `default` option work for specifying a config-path

lib/minimist.js, test/parse.js
see #68, the following:
```javascript
var s = yargs([ '-s' ]).string('s').argv.s;
```
will now return an empty string.
=> flags explicitly set as strings, will now default to '' if no right-hand-value is set

index.js, test/usage.js
Fixes fixes https://github.com/chevex/yargs/issues/71. If yargs was called using:
`require('yargs')(['--foo', 'bar'])`.
`yargs.argv` is not called, which results in the `self.parsed` variable being `undefined`. This patch triggers the parsing step if `help` is executed prior to its first execution.
=> fix for #71

README.md
Added all possible `opt` parameters to the README since that wasn't totally clear from the `.option()`/`.options()` section of the doc. Also added an `.options()` example.
=> clarify opt parameters

README.md, example/complex.js, index.js, lib/parser.js, lib/usage.js, lib/validation.js, package.json, test/helpers/utils.js, test/parser.js, test/usage.js, test/yargs.js
* added the `command` option, which allows you to document the commands that your application accepts:
```
.command('upgrade', 'upgrade the current version of the application')
.argv;
```
* added the `epilogue` option, which allows you to specify a final line of text that your application should output. see: https://github.com/chevex/yargs/issues/14
* added the `array` option (similar to string, or boolean), tells the parser to always interpret a key as an array, even when only a single value is given.
* version now prints with a newline: see: https://github.com/chevex/yargs/issues/81
* based on @nylen's work, window-size is now detected and is used to wrap usage instructions.
* `.check()` will now fail if any non-truthy value is returned. see: …
=> yargs version 3.0 release

lib/parser.js, test/parser.js
There were various bugs surrounding the usage of dot-notation with flag-style variables:
`-f.bar=33`, see unit-tests for details.
=> fix dot-notation logic, surrounding flag variables

README.md, index.js, lib/usage.js, package.json, test/fixtures/config.json, test/usage.js
`.version()` is cool, but you usually want to load the version # programmatically rather than having it hard-coded. This change allows you to optionally pass a function to `.version()`, which can be (as an example) used to load the version # from the package.json.
=> make the version feature more useful

README.md, index.js, lib/parser.js, lib/usage.js, package.json, test/parser.js, test/usage.js
Using a function as a default value resulted in a broken usage message, see #60.
Providing an unnamed function for a default will now result in these usage instructions:
`[default: (generated-value)]`
You can also now provide a named function:
```js
var argv = require('./')
.help('h')
.default('random', function randomValue() {
return Math.random() * 256;
}).argv;
```
which would result in the usage instruction:
`[default: (random-value)]`
what do you think @kilianc?
=> uses function as default value resulted in a broken usage message

README.md, index.js, lib/validation.js, test/yargs.js
* added tests for `reset()` method, it now does a better job of getting yargs into an initial state.
* a better reset command makes it easier to create a nested argument parser \o/
* I've added an example of this to the README.
* I think this is a clean way of addressing the feature request put forward in #53
=> improve and add tests to reset() command

lib/usage.js, test/usage.js
This PR fixes some small typos within the epilog handling for the following use case:
```js
yargs('')
.epilog("Try '$0 --long-help' for more information")
```
=> fix: replace $0 in epilog

index.js, lib/parser.js, lib/usage.js, package.json
We were using the `string` library for camelcase/decamelize helpers, unfortunately string modifies the underlying string prototype which can introduce bugs.
I've switched us to using:
https://www.npmjs.com/package/decamelize
and
https://www.npmjs.com/package/camelcase
we can pull in more string helpers as needed.
fixes #106
=> switch from string to camelcase/decamelize

README.md, index.js, lib/parser.js, package.json, test/parser.js, test/yargs.js
I have implemented `nargs` functionality based on Python's argparse module (see #15). Being able to specify the number of arguments following a flag can help eliminate ambiguity.
e.g., it allows an argument to accept values that would usually be parsed as additional command line arguments (see #78)
```js
.nargs('token', 1)
.parse(['--token', '--my-cool-token']);
```
=> implemented nargs feature, based on Python's argparse

lib/parser.js, test/parser.js
Actually, `count` drops the next argument:
```js
require('yargs').count('verbose').parse([ '--verbose', 'I AM LOST!', 'foo' ])
{ _: [ 'foo' ], verbose: 1, '$0': 'node' }
```
That's because `count` and `boolean` are handled somewhat differently.
Maybe this PR needs some refactoring as I've only doubled the `boolean` checks.
=> fix: count should not consume the next argument

index.js, package.json, test/usage.js
The act of creating the `Argv` singleton was causing the yargs getter to invoke, and causing premature parsing.
=> yargs was parsing more times than it should

README.md
Corrects the `.showHelp` docs by changing the parameter from a function to a `console` function, to match what the code is doing:
https://github.com/bcoe/yargs/blob/master/lib/usage.js#L209
=> Correct `.showHelp` docs

index.js, lib/parser.js, lib/usage.js
This paves the way for cleaner implementation of #127 (as in: no need for `noEval` flag)
=> adjust the way yargs evaluates functions passed as defaults

index.js, lib/parser.js, lib/usage.js, package.json, test/parser.js, test/usage.js
if you swapped the order of the `alias` and the `primary` key, when using the chaining API, options such as: `describe`, `default`, `string`, `require`, would not be shown in the usage string.
* we now make an attempt to apply usage information to both the primary and the alias key.
* coverage has been fixed by using the patched-blanket library.
see: #134, #128
=> the chaining API now cares less about key ordering

README.md
This example is supposed to be demonstrating argument validation, but the example is wrong here.
=> Fix README example in argument requirements

.travis.yml, lib/usage.js, package.json, test/usage.js
I found the logic in yargs for laying out multi-column tables to be some of the most confusing in the codebase. It had grown fairly organically, and we were doing backflips to use the same code for: `commands`, `examples`, and `options`.
Motivated by this, I've created the library `cliui`:
https://www.npmjs.com/package/cliui
Which provides an abstraction for multi-column UIs.
This is a fairly major change, I've tested the usage output with several of my own yargs applications, but I'd love a second set of eyes.
Mind helping with testing? @annonymouse, @nylen, @pirxpilot, @raine
=> refactor yargs' table layout logic to use new helper library

index.js
=> showHelp's method signature was misleading fixes #153

package.json
This pull request changes the value of the license property in `package.json` to a standard, machine-readable SPDX license identifier.
I'll be honest: This is a semi-automated pull request. I started by using [dat](http://dat-data.com/) and [dat-npm](https://www.npmjs.com/package/dat-npm) to review metadata for all packages on [npm](http://npmjs.com), looking for packages that don't use a valid [SPDX license identifier](https://spdx.org/licenses/) in `package.json`. I used my own npm module, [spdx-correct](https://github.com/kemitchell/spdx-correct.js) to guess what license you were after: [`"MIT"`](https://spdx.org/licenses/MIT). A quick manual check and a few shell scripts later, and this pull request was born.
npm doesn't require that you use a valid SPDX identifier, but it's strongly …
=> use a valid SPDX license identifier

README.md, index.js, test/usage.js, test/yargs.js
allows a handling function to be associated with a command see #156 
you can now optionally provide a third argument to `command`, which represents a handler for the function.
This command will get an instance of `yargs` passed into it, which can then be used to parse arguments specific to the command:
```javascript
yargs(['snuh', '-h'])
.command('blerg', 'handle blerg things', function (yargs) {
yargs.command('snuh', 'snuh command')
.help('h')
.argv
})
.help('h')
.argv
```
I found that I tend to write boiler-plate code for a lot of my command-line applications, for facilitating this functionality.
=> allows a handling function to be associated with a command

.coveralls.yml, .gitignore, .travis.yml, README.md, lib/usage.js, package.json, test/parser.js
The language used to explain how `.config()` works is ambiguous. It could be read as saying that `.config("config.json")` would work. I'm not sure that this language is much better, so feel free to change if you think of something better.
=> clarify .config() docs

.coveralls.yml, .gitignore, .travis.yml, lib/usage.js, package.json, test/parser.js
* fixed the failing tests, related to new standard constraints (@linclark you should rebase with this branch).
* added Lin as a collaborator in package.json.
* switched to [nyc](https://github.com/bcoe/nyc), rather than patched-blanket.
* fixed a security issue where the token for coverage was exposed, token has been regenerated.
=> fixed failing tests, along with a few other tiny patches

.gitignore, README.md, lib/parser.js, package.json, test/parser.js
This pull request adds more intuitive parsing of array arguments, based on a discussion with @getify (see #162). Here's how things work now:
`--foo a b c` where `foo` is an array, will now be parsed as `['a', 'b', 'c']`.
This pull request includes fixes for both `array` and `nargs`, adding support for `--foo=a b c`.
=> more intuitive parsing of array arguments see #162

README.md, index.js, test/yargs.js
The terminal width is now exposed by `yargs.terminalWidth()`, this can be used along with `wrap()` to maximize the width of usage instructions.
fixes #155
=> expose the method yargs.terminalWidth()

README.md, index.js, lib/validation.js, test/usage.js
You can now specify a min/max # of non-option arguments, see #169.
It works like so:
```js
yargs.demand(min, max)
```
Where min/max represent the minimum and maximum # of arguments that must be provided.
=> you can now specify a min/max # of non-option arguments

index.js, test/completion.js, test/fixtures/bin.js, test/integration.js
patches for completion brought about by #177:
* there were problems with completing the completion argument itself, related to it attempting to print out the completion script.
* there were problems completing `--help`, caused by the help output firing.
* there were problems related to strict argument parsing, because `--get-yargs-completions` was not whitelisted.
=> patches for completion, brought about by #177

lib/completion.js, test/completion.js
This makes it so a command that is already in the provided arguments will not be one of the suggested completions.  Since yargs doesn't represent commands more than once in the parsed `argv`, I assume this is non-controversial.
However, this does mean that if a program supports both `foo` and `foobar` as commands, typing `program foo[TAB]` would complete to `foobar`.  I could add some additional logic so that both `foo` and `foobar` were suggested completions in this case.  @bcoe would you be interested in support for this?
=> Avoid completing already provided commands

completion.sh.hbs
If calling a script with `--get-yargs-completions` doesn't result in any matches for the current word, we can fall back to the default filename completion.
See suggestion in https://github.com/bcoe/yargs/issues/180#issuecomment-113799086.
=> Default to filename completion if no other matches are found

index.js, lib/completion.js, package.json, test/completion.js
I've made a couple minor tweaks to the command-specific-completion logic in #185 
we now always look for the `get-yargs-completions` option, so `yargs.completion()` only needs to be called when registering a top-level command to generate a completion script.
=> a couple minor tweaks to the command-specific completion logic in #185

README.md, index.js, test/completion.js, test/usage.js
This makes it so calling `yargs.command('some-command', false)` will create a hidden command.  Hidden commands are not shown in the help output and are not eligible for completion.
Fixes #188.
=> Hide commands with false for description

index.js, lib/parser.js, test/parser.js
the magic help argument is now processed before we throw errors, this solves the problem reported in #184.
We also now don't return an error, if the bad configuration file was loaded as a result of a default argument value see #172.
=> tweaks to how errors are reported and config loading is handled

README.md
For consistency.
vs
Low quality paste, but the difference is mainly that travis is now svg instead of png, so looks (much) better on hi-res screens
=> Use shields from shields.io

README.md, locales/fr.json
**`yargs` go international !**
Related to #214 
Added french language. **Still work in progress**. I would like some review from other french speaking people. I'll ask my colleagues but it'll be most better if community can review it too.
Is it a good idea to translate types ? 
I wasn't confortable to translate this kind of words, closely linked with programming and computer science. In current review, it is not translated.
=> Locale French

locales/es.json
=> Added ES locale

index.js, lib/usage.js, locales/en.json, locales/es.json, locales/pirate.json, test/yargs.js
:heavy_plus_sign: Further testing revealed the following strings used in `index.js` were missing from y18n lookup:
```json
"Path to JSON config file": "Path to JSON config file",
"Show help": "Show help",
"Show version number": "Show version number"
```
This PR fixes that.
Note that [the first commit](https://github.com/bcoe/yargs/commit/3a523eb086c4c877f2e837b3ee9f02523e6fe0fa) takes the naive approach, which results in using the `en` version for `'Show help'` in this scenario:
```js
var argv = require('yargs').help('h').locale('pirate').argv
```
[The second commit](https://github.com/bcoe/yargs/commit/01e91c7f9ad51d67f235540567ed8362d97760c6) addresses this by deferring the y18n lookup until the whole usage content is generated, instead of doing it when the option is defined.
Also note …
=> Add missing locale strings to y18n lookup

README.md, lib/parser.js, locales/en.json, locales/es.json, locales/fr.json, test/parser.js
:fr: Some strings were found to be previously missing from y18n lookup; this adds them to `fr.json` with an attempted French translation:
```json
"Path to JSON config file": "Chemin du fichier de configuration JSON",
"Show help": "Affiche de l'aide",
"Show version number": "Affiche le numéro de version"
```
See related discussion in PRs #220 and #221.
@LoicMahieu If you have time, I would greatly appreciate a quick review of these French translations. Thanks!
=> Add missing locale strings to FR locale

index.js, lib/parser.js, package.json, test/fixtures/config.json, test/parser.js
@sgentle made a couple slight tweaks to #223 to make it even more awesome:
* defaulted now takes into account aliases, this way you can have the `help` key set in your config file, and if you have `.alias('h', 'help')` yargs will set both the `h` and `help` key based on your JSON config.
* I made it so that you can specify `config` in the options block, because why not?
```js
yargs.option('config', {
config: true
})
```
reviewers: @sgentle, @nexdrew.
=> a couple slight tweaks to @sgentle's configuration fixes

README.md, lib/usage.js, locales/de.json
This adds German translation as said in the title.
Note: `array`, `string` and `boolean` are untouched because translating them to German rather causes confusion than enlightenment as I experienced it, I think that more people know the English words instead of the German words (if you still want me to translate them, tell me).
`count` is untouched because I'm not certain if I am aware of the context it's used in as I'm not having much experience with this module, could you provide an example? I'll fix it then.
=> Added German translation

README.md, index.js, lib/usage.js, package.json, test/yargs.js
This pull moves us to phase 2.0 of locales in yargs, we now automatically detect the operating system's locale using @sindresorhus' [os-locale](https://github.com/sindresorhus/os-locale) module.
```sh
LC_ALL=pt_BR ./test.js --help
```
outputs:
```sh
Opções:
-h, --help  Mostra ajuda                                             [boolean]
--foo       what up fool                                          [padrão: 99]
--config    i be config yo                             [padrão: "./cool.json"]
-x                                                                [padrão: 10]
```
now we just need to work on getting some more translations.
reviewers: @nexdrew, @nylen
=> detect a user's locale using os-locale

index.js, lib/usage.js, test/usage.js, test/yargs.js
This should fix issues #140 (excluding dot notation problems) and #194.
With this change, you can now do the following:
```js
.option('port', {
defaultDescription: '80 for HTTP and 443 for HTTPS',
default: null || undefined
})
.argv
```
```js
.option('id', {
alias: 'name',
type: 'string',
default: require('moniker').choose,
defaultDescription: 'moniker',
describe: 'The log stream id'
})
.argv
```
And yargs help content will include `[default: 80 for HTTP and 443 for HTTPS]` and `[default: moniker]`, respectively.
Note that I slightly refactored the `default()` method to use this order of precedence for `defaultDescription`:
1. given `defaultDescription` argument
2. predefined `options.defaultDescription[key]` (via `option()`)
3. …
=> Add defaultDescription to option()

index.js, package.json, test/yargs.js
If os-locale throws, we will now default to en when detecting locale.
CC: @sindresorhus, @kevinsawicki, @MatthewNewland
=> hotfix for os-locale on some windows platforms

index.js, lib/parser.js, package.json, test/integration.js, test/usage.js
Required fixing the following nits:
- yargs/index.js:35:8: '?' should be placed at the end of the line.
- yargs/index.js:584:8: '?' should be placed at the end of the line.
- yargs/index.js:585:8: ':' should be placed at the end of the line.
- yargs/test/integration.js:41:4: Block must not be padded by blank lines.
- yargs/test/usage.js:350:6: Block must not be padded by blank lines.
- yargs/test/usage.js:366:6: Block must not be padded by blank lines.
- yargs/test/usage.js:395:6: Block must not be padded by blank lines.
These fixes would be required on next build anyway, according to current `devDependencies` semver range.
=> Upgrade standard to 5.2.x

.travis.yml
Noticed that recent Travis builds included a notice about running on legacy infrastructure. According to [the migration docs](http://docs.travis-ci.com/user/migrating-from-legacy/), moving to the new infrastructure is as easy as adding `sudo: false` to `.travis.yml`.
Let's give it a shot.
Again, expecting `standard` to fail until PR #247 is merged.
=> Migrate to new Travis container-based infrastructure

.travis.yml, appveyor.yml, package.json
Also opted to drop Node v0.11, to keep number of builds the same (4 per platform) while still (theoretically) covering the same range (v0.10 - v4).
To make AppVeyor config consistent with Travis, also changed `3.0` to `3` to use latest iojs version (e.g. 3.3.1) instead of latest 3.0 version (which is always 3.0.0).
Note that, at least for Travis, we could use `stable` instead of `4` (to anticipate version 5+), but I decided to stick with prior convention.
Also note: I expect the build to fail (at the moment) for Node v0.10 until [issue 14 of `standard-engine`](https://github.com/Flet/standard-engine/issues/14) is fixed. Looks like we could revert our `standard` dependency back to version `5.0.0` to workaround this, but then we'd have to remember to update it once the `eslint` git …
=> Add Node v4.x to CI builds

README.md
=> Remove util in README.md

README.md
Specifically meant to address #262, but found other things that needed to be fixed as well.
Summary of changes, grouped by commit:
- [1d12ff4](https://github.com/bcoe/yargs/commit/1d12ff4d89cc236205948b1098e1d7b2e6af3205): Move `detectLocale()` to be in alphabetical order with other methods
- [ec3bb4e](https://github.com/bcoe/yargs/commit/ec3bb4e433e8863aa20fca485a1039b720ab6f23): Add `ja`/Japanese to supported locale list (missed in PR #254)
- [9c40604](https://github.com/bcoe/yargs/commit/9c40604f45a55784c30d68cc58e196c69b774b70): Augment `option()` documentation to include all valid properties (fixes #262)
- [66c96e3](https://github.com/bcoe/yargs/commit/66c96e3f100f247aa0b203e223a79189b15ef0ed): Add `count()` method documentation
- …
=> Document option() object keys and other README improvements

test/parser.js
Another argument parsing library had a problem with `--` after `--`, here I add extra data to test that and various other edge cases in your comprehensive parser test.
=> Add more cases to comprehensive parser test.  Mainly for -- .

lib/usage.js, test/usage.js, test/yargs.js
Fixes issue #270 (concerning when `.exitProcess(false)` is used) by implementing the simplest solution mentioned [in comment](https://github.com/bcoe/yargs/issues/270#issuecomment-144551525) there.
Includes and satisfies test specs from PR #269.
=> Output failure message only once

index.js, test/usage.js
Currently if `exitProcess=false` and the help or version options are given the arguments will be validated anyhow.
I'd argue that this is never the desired behavior. For example, if there are required arguments then if the users enters `node . --help` he would get errors for every required arguments missing.
This PR fixes this.
=> Don't validate arguments if help or version is used and exitProcess=false

package.json, test/usage.js
I've updated the layout logic in cliui to take into account the ansi escape codes:
https://github.com/bcoe/cliui/pull/11
https://github.com/bcoe/cliui/pull/12
=> upgrade to version of cliui that handles ansi-colors

index.js, lib/parser.js, test/parser.js
fixes #279 addresses several parsing issues brought up by @mir3z in #279:
* an alias referencing an inner key was not respected (weird things happened like the inner object being turned into an array).
* an outer `foo.bar` key was being set by the `setPlaceholderKeys` method.
* an exception could be created by setting an object key equal to a non-object value.
I'd love an extra set of eyes on these changes, since it's always a bit frightening to muck with the guts of the yargs parser: CC: @mir3z, @nexdrew
=> fix dot notation parsing issues brought up in #279

README.md, index.js, lib/usage.js, package.json, test/usage.js
Allow options to be placed in groups under headings other than the default `Options:` heading, like so:
```js
var yargs = require('yargs')(['--help'])
.help('help')
.group('batman', 'Heroes:')
.describe('batman', "world's greatest detective")
.argv
```
***
Options:
--help  Show help                                                    [boolean]
Heroes:
--batman  world's greatest detective
This is a first pass at tackling #274, which proposes a solution that should help address several aggregate issues: #152, #260, #261 
I was originally trying out @nexdrew's suggestion in #274 of tacking parameters in the order `group, options` as I started writing tests, this felt too weird to me, as it deviated from other options -- it actually made me think we should clean up any other options that …
=> allow options to be placed in custom groups

index.js, test/parser.js
In the ongoing effort to make yargs unsinkable, this pull request handles edge-cases when setting aliases. This behavior used to fail:
```js
.alias('x', 'y')
.alias('y', 'z')
```
As did this:
```js
.alias('z', 'zm')
.alias('zoom', 'zoop')
.alias('zm', 'zoom')
```
We're now clever about merging together alias groups as aliases are defined, solving these transitive edge-cases ... definitely an edge case, but I'm a bit OCD about making yargs handle every edge-case I think of!
reviewers: @nexdrew
=> handle edge-cases when setting alias keys

lib/usage.js, package.json, test/usage.js
it solves https://github.com/bcoe/cliui/issues/14
=> Fix cjk width problem on usage table

locales/tr.json
~~Need context for "count", it has different translations for noun and verb.~~
- Left javascript type names in English. I believe translations would lower the quality of understanding.
=> Turkish translations

README.md, index.js, lib/parser.js, test/parser.js, test/yargs.js
First stab at env var support, implementing [@bcoe's suggestions](https://github.com/bcoe/yargs/issues/305#issuecomment-160851479) as discussed in #305.
This will allow env vars matching a given prefix to be parsed and applied to `argv` via simple configuration method `.env('PREFIX')`. Prefix can be omitted to apply _all_ env vars to `argv`.
Aliases and type configuration are supported when args are defined by env vars.
New order of precedence for program argument values:
1. CLI flags
2. Config file (if configured)
3. Env var (if configured)
4. Default values (if configured)
There is also a special case to support specification of a config file via env var.
For more details, consult the additional README content or the unit tests.
Things not addressed by this PR:
- Indication of env var …
=> Apply env vars to argv via prefix-based API

README.md, index.js, test/yargs.js
until we can sit down and start overhauling how the command functionality works (I think this will be what drives us to `yargs@4.x`), I think this might be a good stop-gap to make commands more useful.
If someone wants to use some top-level options in their command handlers, they can now do this by using the outer `argv` which is passed as the second argument to the command handler.
I found myself wanting this for a command line app I'm working on today.
What do you think of this @nexdrew, is it a worthwhile tweak?
=> pass argv as a second argument to command handlers

package.json
Since the tests on travis are performed against Node 0.10 and higher, stating versions below 0.10 as compatible seems wrong.
=> Changed "engine" in package.json

CHANGELOG.md, README.md, index.js, lib/parser.js, package.json, test/fixtures/config.txt, test/parser.js, test/yargs.js
Allow a custom parsing function to be passed to config.
Fixes #304 
Reviewers: @sebastienbarre, @indieisaconcept, @nexdrew
=> allow a custom parser to be passed to config()

README.md, index.js, lib/usage.js, test/usage.js
This pull request changes the version() API to solve the inconsistency as raised by @bcoe in #329
=> Fix .version() API inconsistency

CHANGELOG.md, README.md, index.js, lib/tokenize-arg-string.js, test/tokenize-arg-string.js, test/yargs.js
@kellyselden made the great suggestion that yargs be able to handle a raw argument string, prior to it being parsed by the OS. Like so:
```js
var a1 = yargs.parse('-x=\'marks "the" spot\' --foo "break \'dance\'"')
```
One great advantage to this is that it makes yargs easier to embed in unorthodox environments, .e.g., a REPL in the web-browser.
fixes #327
=> allow yargs.parse() and yargs(foo).argv to accept a raw argument string

index.js, test/usage.js, test/yargs.js
Fixes #336.
And make sure an option is added to a group only once.
First commit contains failing tests to demonstrate the problems.
Second commit fixes the failing tests.
=> Clear groups in reset method

test/usage.js
@kellyselden look what your feature request allowed us to do to tests \o/ sign of a great feature idea.
CC: @nexdrew
=> split(' ') is no longer needed in tests

CNAME
As per @nexdrew 's suggestions in yargs' [github.io](https://github.com/yargs/yargs.github.io/issues/1#issuecomment-168469258) discussion. :sparkles:
=> removing cname from outdated repository

package.json, test/before.js
This fixes a bug where the unit tests were expecting yargs' output to be in English, which means that tests, checking for equality with prewritten outputs in English, will fail on machines where yargs will detect and use another locale than English.
=> Make yargs use English locales in tests

README.md, index.js, package.json, test/usage.js
This is an update to @maxrimue's awesome work adding tests.
I found the test cases slightly tricky to simulate, I ended up:
1. copying the current yargs module to a fixtures directory so that I could test the normal behavior.
2. creating a symlink in the fixtures directory so that I could test the symlink behavior.
I would love thoughts from @sindresorhus, and @nexdrew as to how we might simply this testing logic.
=> default to the version we read in the package using yargs

.gitignore, .npmignore
I'm thinking about using Yargs in a [super exciting project](https://www.npmjs.com/package/cash), but due to the nature of the project, performance and package size is a big issue.
Yargs unnecessarily publishes a 44kb changelog - *very* important on the Github repo, but not so much in a published module dependency.
Can we remove this please? You'll make many projects that much snappier. :smiley:
=> Remove changelog from published NPM package

.gitignore, .npmignore
Need to undo #354 since npm will always include `CHANGELOG` file according to https://docs.npmjs.com/misc/developers
=> fix .gitignore and rm .npmignore

README.md, index.js, test/usage.js
This takes care of @bcoe's idea in #367
=> Made help() only assign '--help' option if called without args

README.md, index.js, lib/validation.js, test/usage.js, test/validation.js
Check if `argv` provided is in `commandHandlers` if using `.strict()`.
A WIP pull for #174
=> require valid command

index.js, lib/usage.js, lib/validation.js, test/usage.js
A follow up to https://github.com/bcoe/yargs/pull/374
=> Pass the original error as the second argument of fail() handler. (fixes #373)

CHANGELOG.md, README.md, index.js, test/yargs.js
You can now call `yargs.pkgConf('configKey')` which will tell yargs to load defaults from a key in your package.json, snazzy!
=> introduces pkgConf feature

lib/command.js, test/usage.js
Just need to check for module command _before_ adding it to usage; otherwise the recursion adds it twice. Includes test to guard against regression.
=> Do not include module commands in usage text more than once

lib/usage.js, test/usage.js
Preserve the "global" `wrap()` value so that usage width is consistent for commands that do not wish to override it (particularly when using an options object instead of a builder function). Commands that wish to override it may still do so.
Includes a test for each scenario.
=> Do not reset wrap for commands

index.js, test/usage.js
Heya! I used yargs in a new CLI tool the other day. This tool takes some global options as well as per-command options. I noticed I had to [restore the global option groups](https://github.com/novemberborn/wilee/blob/cdf47828ae17dd9ffd3944def85adf189205f403/src/lib/cli.js#L45) for each command, which I was not expecting.
With this PR I'm proposing that groups containing global keys are preserved within commands. Please let me know if that's a sensible thing for yargs to do!
One concern raised in #336 is the ability to control the order of the groups in each command's help output. Currently this PR puts the groups with global keys first. Possibly the `groups` object could be reordered if the group is redeclared without keys.
I also may be misunderstanding the myriad uses of …
=> Preserve groups containing global keys

lib/command.js, lib/usage.js, test/usage.js, test/yargs.js
I like the feature of using the original command string as the `usage()` string for commands that pass an options object instead of a builder function.
I thought it'd be cool to give commands with builder functions the same treatment as long as they don't:
1. parse argv in the builder function itself (in which case a `--help` flag would have already triggered usage output)
2. explicitly set the `usage()` string in the builder function
This is totally subjective and so is up for debate, but I think keeping the different command approaches as similar as possible is a good idea that could lead to more interesting features down the road (e.g. command suggestions, etc).
Also not sure if this "breaks" user expectations based on 3.x functionality, but hey, this is 4.x.
=> Use implicit usage string when not set by command builder function

README.md
Includes other minor cleanup/clarification to make the text more consistent with other content.
Note that we generally use square brackets in docs to represent optional args rather than arrays.
=> Alphabetize `number` in README docs

lib/command.js, test/command.js, test/fixtures/command-module.js, test/yargs.js
This just expands support for command modules such that the command string and description can also be defined by the module, like so:
```js
// foo.js
module.exports = {
command: 'foo <bar> [baz]',
describe: 'foo all the things',
builder: function (yargs) { return yargs },
handler: function (argv) {}
}
```
```js
// cli.js
.command(require('./foo.js'))
.argv
```
A command string must be provided by the `command` property (and it must be a string).
A description is optional. If not provided, the command will be "hidden". If provided, it can be a string or a boolean, and for consistency with the options API it can be provided by a `describe`, a `description`, or a `desc` property (in that order).
I see this as an incremental step toward allowing command modules to …
=> Allow command modules to define all command properties

yargs.js
It wasn't causing any issue, but this should save a few iterations in `arrayOptions.forEach`
=> Remove duplicated option keys from arrayOptions

test/usage.js, test/validation.js
I left these to provide only `cmd` and `desc`, as they are only testing `fail` outputs in `validation` and `usage`.
closes #429
=> fix tests that use .command() improperly

lib/validation.js, test/validation.js
Fixes #444
Note that `commandKeys` is an array, not an object, so I replaced the use of `hasOwnProperty()` with `indexOf()` to account for inherent Array properties like `length`.
=> Check for commands before validating argv._ in strict mode

lib/usage.js, test/usage.js
Motive: in tests I don't want yargs to print anything to the console. But I do want to catch it and see that it try.
So - when I pass it the handler itself - let it write to this handler.
Consider the following use-case scenario:
```
var yargs = require('yargs');
var options = { ... }; 
module.exports = function args(process, log)  {
var args = yargs.usage("foo").help().options(options).parse(process.argv);
if (!log) log = console.log; //injected in test time, defaults to console.log;
if (args.help) {
yargs.showHelp( log )
process.exit();
return;
}
return args
}
```
then, in tests
```
var sut = require('../lib/args')
describe("lib/args", function() {
describe("when provided with help switch", function() {
var logs = [];
var mockProcess = { env: { ... }, argv: [ .... ], exit: function() { …
```
=> showHelp getting the emission function itself

completion.sh.hbs
A little background: When executing a completion function, Bash sets the `COMP_WORDS` array containing the individual words in the command line. If the cursor is at the end of the line (after the last word and separated by a blank), an **additional null word** is added to `COMP_WORDS`. That way the completion function can tell if the user is trying to complete the last word, or a new word after it.
The issue here is that we aren't sending the last null word to yargs because bash's word splitting removes unquoted nulls.
This PR should fix it. It uses the **“${name[@]}”** form to send the words, which preserves them all.
=> Fix bash completion when COMP_WORDS has a null word

test/usage.js, yargs.js
Specifying a command count and required arguments at the same time causes the required arguments to be set as the 'max' of argv._
For example, calling `.demand(1, ['foo', 'bar'])` causes this to be set in options.demanded: `_: { count: 1, msg: undefined, max: [ 'foo', 'bar' ] } }`
This doesn't really fails because, when doing the validation, comparing a number to an array returns true most of the time on Javascript. But we shouldn't be relying on undocumented behavior if possible.
There is actually an edge case that fails: When calling `.demand(1, ['1'])`, it will fail is the user provides more than one command. I added a test for that.
=> Fix demand() when second argument is an array

lib/command.js, lib/validation.js, test/command.js, test/usage.js, test/validation.js, test/yargs.js, yargs.js
This is something I've wanted to do for a while but never had a good grasp on how to implement it. (And, I arguably still don't. :grinning:)
However, issue #426 brought up a good first use-case for maintaining a context of command execution, in order to change the behavior of "unknown argument" validation (induced by `.strict()`) based on if it's running for a (possibly nested) command or not.
As is, this branch fixes that problem - without breaking any existing tests - but is still lacking tests for the scenarios it addresses.
The reason I'm opening this PR now is that I'd like some feedback on the approach/implementation before I put much more effort into it. Basically, I'm adding another piece of state (tied to the yargs singleton) that does **not** get reset for command execution, but …
=> Introduce command execution context

README.md
Based on the way `.help()` is documented
=> Update documentation to say that 'cmd' can be omitted in .completion()

README.md, test/validation.js, yargs.js
Before this, if you called `.config()` without parameters, an option named `'undefined'` is set to receive the config file. I propose to set the default name `'config'`.
This way it works just like `.help()` and `.completion()`.
=> If invoking .config() without parameters, set a default option

README.md, locales/en.json, locales/it.json
1. Include `command` and `describe` props for command modules (since #414)
2. Include `Error` instance as 2nd arg for fail handler (since #382)
3. Sync up locale list with locale files
Also added missing `"number"` string to American English and Italian locales. (I think my Italian translation is correct. :smiley:)
=> Add missing features to README docs

README.md, lib/command.js, test/command.js
Introduces the concept of variadic commands arguments. I'm feeling like along with @nexdrew's work in https://github.com/yargs/yargs/pull/428 commands are getting pretty darn slick. You can now do: 
`./my-bin.js open file-1 file-2-file-3`
and get,
````js
{files: ['file-1', 'file-2', 'file-3']}
```
=> variadic positional arguments

CHANGELOG.md, package.json
I'm sick of maintaining a hand-rolled artisanal changelog, switching to using the conventional-changelog angular format:
https://github.com/stevemao/conventional-changelog-angular/blob/master/convention.md
=> introduce conventional-changelog

test/usage.js, yargs.js
I made some changes to the way the `$0` variable is created, so that the Windows version matches the Linux one:
- It ignores `argv[0]` if it ends in "node.exe" or "iojs.exe"
- It allows to use the rebased version of `argv[1]` if it uses Windows style paths
Now, the tricky part is that I had to make platform dependent tests, because the behavior of `node.path.relative` changes depending on platform, and there's not a straightforward way to mock it. Let me know what you think.
=> Improve $0 in Windows

lib/completion.js, test/completion.js, test/integration.js
This makes sure that an option won't be suggested for completion if the option, or any of its aliases, is already in the provided arguments.
Pretty much the same thing that was done for command completion in https://github.com/yargs/yargs/pull/183
I figure this is a good start, but it only checks options in **long form**. Checking for short form depends on whether 'short-option-groups' is enabled or not, and would need to duplicate parts of the parser logic, so it is a bit tricky.
I also had to modify slightly the integration test that checks that the completion for '--help' works. Now it won't complete if the current word is '--help', so I made it try to complete '--h'
=> Avoid repeating options in completion

package.json
yargs is great because it's:
* full-featured.
* a slick API.
* pirate-themed.
Lightweight, it's not so much anymore. I suggest we change the description in `package.json` to match the repo.
CC: @nexdrew, @osher 
fixes: #468
=> fix(brand): I agree with @osher lightweight isn't a huge selling point any longer

README.md, yargs.js
=> docs(default): Document deprecated alias of default()

README.md, test/yargs.js, yargs.js
`.skipValidation()` takes a key. If the key is present, validation won't be performed.
Closes #453
=> feat(validation): Add .skipValidation() method

README.md, test/yargs.js, yargs.js
=> feat(configuration): Allow to directly pass a configuration object to .config()

README.md, test/yargs.js, yargs.js
Update `.pkgConf()` to use the new `configObjects` option from yargs-parser, this way the aliases issues are solved.
Change wording of `.pkgConf()` tests and description as it no longer works by setting defaults, and add some further tests.
=> fix(pkgConf): fix aliases issues in .pkgConf()

README.md, lib/completion.js, test/completion.js, yargs.js
Add new method `.getCompletion(args, done)` which receives an array of strings representing a line to complete, and calls the `done` callback with the resulting completions.
Update the completion tests to pass the arguments explicitly to yargs. We can't pass them by mocking `process.argv` now because `process.argv` is only checked on `index.js`, which is called before the tests can apply the mock.
=> feat(completion): allow to get completions for any string, not just process.argv

index.js, lib/command.js, lib/completion.js, lib/obj-filter.js, lib/usage.js, lib/validation.js, yargs.js
Philosophy behind this: http://womack.io/2016/01/05/Const-ant-Craving/
tldr;
* `const` has been supported in Node.js since at least 0.4
* `const` makes code more readable—it's clear a value won't change
* standard helps w/ this by pointing out when `const` is misused
=> fix: use const as a semantic tool

README.md, lib/command.js, package.json, test/command.js, test/fixtures/cmddir/deep/deeper/deeper_still/limbo.js, test/fixtures/cmddir/deep/deeper/inception.js, test/fixtures/cmddir/deep/of-memory.json, test/fixtures/cmddir/deep/within-a-dream.js, test/fixtures/cmddir/dream.js, test/fixtures/cmddir_cyclic/cyclic.js, yargs.js
This replaces #463, opting to require modules from a single directory at a time via `require-directory` (instead of supporting globs).
The implementation is slightly trickier than I originally thought, but it allows a consumer to do things like the following.
**directory structure**:
```
cli.js
commands/
people.js
places.js
things.js
common_cmds/
details.js
search.js
people_cmds/
call.js
places_cmds/
nav.js
```
**cli.js**:
```js
#!/usr/bin/env node
// apply people.js, places.js, things.js but not subdirectories
.commandDir('commands')
.help()
.wrap(40)
.argv
```
**commands/people.js**:
```js
exports.command = 'people <command>'
exports.desc = 'Work with people'
exports.builder = function (yargs) {
// apply commands in subdirectories
return …
```
=> Add .commandDir(dir) to API to apply all command modules from a relative directory

lib/command.js, package.json, test/command.js, test/fixtures/cmddir_noname/nameless.js, test/yargs.js
Mentioned in #494, this PR makes a `command` string optional for module-based commands, using the base filename of the `require()`d module for the command when the `command` string is not specified/exported.
Not only does this get us one step closer to implementing #492, but it also paves the way for supporting an "auto" mode for `commandDir()`, where conventions can be used to determine subcommand hierarchies and command names can be defined by filenames of submodules.
In this implementation, a `command` string is derived by filename via the following:
- For `.command()`: filename is looked up in `require.cache` via the new [`which-module`](https://github.com/nexdrew/which-module) dependency
- For `.commandDir()`: filename is already available via the `require-directory` API
This logic …
=> feat(command): derive missing command string from module filename

README.md
As it seems, it's still unclear how commands actually behave when it comes to configuration. This is probably because of that information missing in the documentation.
These new lines are meant to make clear that commands do not inherit the configuration of their parent context, which means that users have to re-apply configurations they want to keep across scopes.
What does everyone think?
=> Added documentation about commands not inheriting configurations

test/command.js, yargs.js
We were applying commands in the order that handlers were defined, rather than the order of `_`, fixes #514
=> fix: we now respect the order of _ when applying commands

index.html
Instead of having Flatdoc render the README from master, let's query the registry for the `latest` published version of yargs and tell Flatdoc to use the corresponding tag in GitHub.
This should fix the [problem where ](https://github.com/yargs/yargs/issues/529#issuecomment-226997791) [our docs are out-of-sync ](https://github.com/yargs/yargs/issues/529#issuecomment-228461862) [with what's actually published](https://github.com/yargs/yargs/issues/529#issuecomment-229407166).
Note that this introduces a dependency on an external service (https://jsonp.afeld.me/) in order to wrap the JSON from the public npm registry in a JSONP response, to get around the lack of CORS support in the registry. We could use [YQL](https://developer.yahoo.com/yql/) as a "more stable" alternative, but that would …
=> feat: use readme from latest published version instead of master

package.json, yargs.js
we dug into some of the performance concerns with yargs in #521, and came up with an initial quick win.
In this pull request we:
* eliminate `pkg-conf` in favor of using `read-pkg-up` exclusively.
* we lazy-load `read-pkg-up` (the require time for modules was leading to some of yargs' bad performance benchmarks).
* we cache the `package.json` the first time we load it.
=> fix: lazy-load package.json and cache. get rid of pkg-conf dependency.

test/fixtures/package.json, test/yargs.js, yargs.js
Fixes the small bug mentioned here: https://github.com/yargs/yargs/pull/544/files#r70469421
Includes test 😎
=> fix: cache pkg lookups by path to avoid returning the wrong one

lib/command.js, package.json, test/command.js, yargs.js
Pull in [`get-caller-file`](https://github.com/stefanpenner/get-caller-file) to always interpret the directory given to `.commandDir()` as relative to the caller. This actually helps simplify the logic a good bit since I no longer need to keep track of a command-to-dir mapping between calls.
The `require` is deliberately lazy, so we only load the dependency if `.commandDir()` is called.
There are a few different packages that provide the "get filename of caller" functionality, but I chose `get-caller-file` because it was the only one that already had passing tests for the range of Node we need and includes Windows tests ([`caller`](https://github.com/totherik/caller) seems to be popular but is lacking the fuller range of testing, and [`caller-path` seems to be broken on Node …
=> fix(commandDir): make dir relative to caller instead of require.main.filename

test/command.js, yargs.js
=> fix: positional arguments were not being handled appropriately by parse()

package.json, test/integration.js
While we're at it, stop using the `cross-spawn-async` dependency which is deprecated.
=> fix: pull in @nexdrew's fixes to yargs-parser

README.md, test/command.js, test/yargs.js, yargs.js
In addition to a flagged option (e.g. `--help`), `.help()` now also supports an implicit command (e.g. `help)`, which is enabled by default.
This means any yargs CLI can now enjoy commands such as:
```console
$ cli help
$ cli help command
$ cli command help
```
No flag needed. 😎 
I opted to build the implicit command into the existing `.help()` API (instead of creating a new method) in order to:
1. reuse the same tokens for the flag and the command
2. enable it by default for most uses of `.help()`
It can be explicitly disabled by passing `false` as one of the 3 arguments.
Note that any help option aliases will also be used as an alias for the command, as long as:
1. the alias has a length greater than 1, or
2. all aliases have a length of 1
This should be considered a 5.x breaking change …
=> feat: .help() API can now enable implicit help command

lib/command.js, test/command.js, test/yargs.js
Fixes #522.
~~I'm not quite sure about the intentions of what should be allowed to be returned by the builder function. Returning the `yargs` instance or nothing should now work, but I wonder if we ever intended to allow it to return something like `yargs.argv`? If so, I think we will need a new issue for that.~~
Otherwise, this PR seems to work fine, but it could possibly result in unexpected behavior in user CLIs if they were previously not returning the `yargs` instance, either by mistake or not. For that reason, this change may be better suited for 5.x.
Note that I skipped the `populates argv with placeholder keys when passed into command handler` unit test because this change breaks it and it no longer seems to be valid (options must now be marked `global: true` in order to apply to …
=> feat(command): builder function no longer needs to return the yargs instance

yargs.js
Remove an alias of the `default()` method, called 'defaults', that was added to avoid usage of
a reserved word (https://github.com/yargs/yargs/commit/1bd4375e11327ba1687d4bb6e5e9f3c30c1be2af)
This isn't actually needed because a method name is a fair use of reserved keywords in Javascript.
=> fix(default): Remove undocumented alias of default()

test/command.js, test/yargs.js, yargs.js
Fixes #486.
This means that a configured `envPrefix` will not be reset for nested commands.
This could potentially be considered a breaking change since env vars that used to be ignored for the execution of command handlers may no longer be ignored. 😮 Otherwise, this could be considered a fix. 😕
=> feat: apply .env() globally

lib/validation.js, test/validation.js
Fixes #451.
Previously, min and max values passed to `.demand()` were interpreted as the _total_ number of non-option arguments, which included the arguments representing the command(s) itself.
With this PR, the min and max values are now interpreted as the _additional_ number of non-option arguments, relative to the currently executing command.
Here's an example:
```js
.command(
'lint',
'Lint a single file',
(yargs) => yargs.demand(1, 1),
(argv) => console.log('linting file:', argv._[1])
)
.argv
```
Before this PR, the command would not work as expected (i.e. would not accept any flagless args) because the `lint` command itself would satisfy the min and max on the command line.
```console
$ program lint
linting file: undefined
$ program lint example.js
program lint
Too …
```
=> feat: interpret demand() numbers as relative to executing command

lib/command.js, lib/usage.js, test/completion.js, test/usage.js
Addresses this TODO from #545:
> TODO: default to a noop builder in yargs@5.x
When implementing this, I discovered it was necessary to either (a) change the expectations of some tests to move a top-level `.fail()` handler to a command-specific one or (b) start applying `.fail()` handlers globally. I opted for the latter due to [conversation in #539](https://github.com/yargs/yargs/issues/539#issuecomment-230987860).
Therefore, this PR solves 2 main problems:
1. Do not require a command to specify a builder in order for validation to apply
Prior to this, code such as `.command('hi').demand('name').global('name')` would not enforce the globally required `--name` option when `hi` is given on the command line, which [has been outlined …
=> feat: apply default builder to command() and apply fail() handlers globally

README.md, lib/command.js, test/yargs.js, yargs.js
Closes #535.
Builds on top of yargs/yargs-parser#42 and yargs/yargs-parser#47.
Adds a `.coerce()` method that allows users to map a coercion (or transform) function to specific option keys. Coercion is then delegated to `yargs-parser`.
The new method accepts the following:
- a single key and a function
- an array of keys and a function
- an object mapping keys to functions
The `.option()` method was also augmented to support a `coerce` property.
Note that, in commit 46eaa9e, a special case of coercion logic was needed to support positional and variadic args for commands. This is because `yargs-parser` does not populate positional args in `argv` - those are populated in `lib/command.js` after parsing is complete - and so it was necessary to duplicate the execution of coercion functions …
=> feat: add coerce api

README.md, lib/levenshtein.js, lib/validation.js, locales/de.json, locales/en.json, package.json, test/yargs.js, yargs.js
working from @maxrimue's branch for `recommendCommands()`, and implementing @nexdrew's code-review.
This pull request gets us to `v1` of command recommendations (thanks @maxrimue for the hard work) addressing some of the nits in #562 (@maxrimue sorry for @nexdrew and I providing such a difficult review).
Here's a breakdown of some of the changes made:
* rather than pulling in another dependency, I simply added a helper module for calculating levenshtein distance: this is a fairly simple algorithm, and I could imagine us using it in other places -- might as well dance around adding another dependency to yargs.
* we now handle the edge-case that @nexdrew outlined with nested arguments significantly better, by avoiding making recommendations until after we've walked through all the command …
=> feat: adds recommendCommands() for command suggestions

lib/command.js, lib/usage.js, yargs.js
Mainly since recent [benchmarks](https://github.com/yargs/yargs/issues/521) show that preloading a bunch of dependencies is the biggest performance killer in yargs. Let's just give deps the same "require on demand" treatment, especially for ones that are only used in certain cases.
=> perf: defer requiring most external libs until needed

lib/command.js, test/command.js
Changed the parsing of the command string to ignore extra spaces between positional arguments, rather than create an additional required positional argument with a value of an empty string for each extra space. Wrote a test to confirm the fix.
=> #540 - Changed parsing of the command string to ignore extra spaces

README.md
This one drove me crazy until I finally figured it out. Because [the default configParser implementation](https://github.com/yargs/yargs-parser/blob/cc4dc5663bf9a29527127cf575d37b461c1c47a2/index.js#L426) loads the file using node's `require`, it breaks if your config file is named `.my-app.conf` (for instance). Short term solution: just mention that! (It's easy enough to workaround using a custom parser function.)
=> docs: mention config file names must end in .json

lib/usage.js
Hi :wave:, I'm a big fan of yargs, so after talking with @lrlna about https://github.com/yargs/yargs/issues/521, I wanted to try my hand at improving the overall runtime of `require('yargs')`.
I started by profiling with the Chrome dev tools using `node-nightly` and the `--inspect` option, where I noticed that `windowWidth()` is a very expensive function:
Since `windowWidth()` only has to be calculated when we need the column width, e.g. when the user has typed `--help` or `-h`, I figured we could lazily evaluate it. That's what this PR does.
Here is a very small benchmark to demonstrate the perf improvement:
```bash
time for i in {1..500}; do node -e 'require("./index")'; done
```
Running in node 5.12.0 on a 2013 Macbook Air, I got the following results (real time, averaged):
* …
=> Defer windowWidth() to improve perf for non-help usage

yargs.js
I am looking at adding something to yargs and in the process of getting familiar with the codebase, I came across [this block of code.](https://github.com/yargs/yargs/blob/master/yargs.js#L405-L441) 
At first glance, due to indentation, it looks like nested `if/else if` blocks. This can be confusing when reading the code. Only after further examination did I notice that these blocks actually aren't connected in the same way `if/else if` blocks are. 
I don't see this style being used elsewhere, it doesn't seem to be a violation of standard style, and I feel like this improves readability.
Obviously, this is a style choice, so if people disagree I am happy to close this PR.
=> Clean up indentation in options block

README.md, test/yargs.js, yargs.js
Usually, yargs always requires options to be featuring an object for customisation like so:
```javascript
yargs()
.option('x', {})
.argv
```
This however seemed strange to me, as said customisation never is needed, you can also use options without any further customisation.
This Pull Request removes the check for whether an object is given to allow for declaration of options like this:
```javascript
yargs()
.option('x')
.argv
```
Why would we do that? Because it the object isn't needed anyway, requiring it makes little sense, and it might be confusing to people. Also, some people (like me) might prefer to write down all options in the yargs configuration to make clear which ones exist, also making yargs list them in the `argv` object even if not passed.
=> make opts object not required anymore for .option()

test/yargs.js, yargs.js
When an arg is defined, it will always exist in the parsed argv. Thus, validation would always be skipped, regardless of whether an arg that has `skipValidation` set to `true` is actually passed on the command line. This commit checks to see if the parsed argv value is actually set to true.
=> For args that have skipValidation set to `true`, check if the parsed arg is `true`

package.json
I'd like to continue supporting Node 0.10 in the medium term, since this is a widely used utility library.
=> chore: add greenkeeper ignore rule for string-width, which no longer Node 0.10

lib/assign.js, package.json, yargs.js
lodash.assign is now deprecated; given how simple our use-case is, I opted to simply add the functionality to yargs itself.
=> fix: drop lodash.assign

README.md, lib/command.js, lib/usage.js, locales/de.json, locales/en.json, test/command.js, test/usage.js
Allows a command to have aliases if given as an array, e.g.
```js
.command(['start', 'run', 'go'], 'Start the app', builder, handler)
```
The first element in the array is treated as the canonical command, which supports positional args; the remaining elements are considered aliases. Aliases inherit their positional args from the canonical command and, thus, any positional args defined for an alias are ignored.
For example, all of the following are equivalent and only the `<name>` required positional arg will be parsed/validated:
```js
.command(['hi <name>', 'hello'], 'Say hi', builder, handler)
.command(['hi <name>', 'hello <name>'], 'Say hi', builder, handler)
.command(['hi <name>', 'hello <someone> [others..]'], 'Say hi', builder, handler)
```
For help text, command aliases are …
=> feat: initial support for command aliases

locales/hi.json, locales/id.json
Otherwise y18n will blow up when attempting to lookup the singular/plural version of the localized string:
```js
.option('f', {
alias: 'foo',
desc: 'foo for thought',
requiresArg: true
})
.option('b', {
alias: 'bar',
desc: 'a dog and a cat walk into a bar...',
requiresArg: true
})
.argv
```
Before this fix:
```console
$ LANG=hi_IN.UTF-8 node locales.js -f -b
विकल्प:
-f, --foo  foo for thought
-b, --bar  a dog and a cat walk into a bar...
Cannot read property 'indexOf' of undefined
```
After this fix:
```console
$ LANG=hi_IN.UTF-8 node locales.js -f -b
विकल्प:
-f, --foo  foo for thought
-b, --bar  a dog and a cat walk into a bar...
कुछ तर्को के मूल्य गुम हैं: f, b
```
Also took the opportunity to make the id locale consistent with others in terms of where each localized …
=> Fix the Hindi locale file

lib/command.js, package.json, test/command.js, test/yargs.js
Populate argv object with camelcase variants of hyphenated arguments.
Fixes #653
=> feat(command): add camelcase commands to argv

README.md, test/yargs.js, yargs.js
This adds 3 things to the existing `headless-yargs` branch:
1. Changes `.parse(msg, cb)` so that the original `exitProcess` setting is reinstated after callback invocation
2. Resets the `parseFn` after each call such that you can mix and match `.parse(msg, cb)` calls (where `cb` is invoked) and `.parse(msg)` calls (where no callback is invoked)
3. Adds a note to `parse()` docs about implicitly (and temporarily) disabling the `exitProcess` setting when providing a callback
Includes tests to verify the functionality of 1 and 2.
reviewer: @bcoe
=> Suggestions to improve headless yargs

lib/command.js, lib/usage.js, lib/validation.js, test/yargs.js, yargs.js
Otherwise, if you `parse(msg1, cb)` a message that executes a command and then `parse(msg2, cb)` a message that *doesn't* execute a command, the second invocation will have lost all top-level state like `.strict()` and `.demand(1)`.
Added test for this scenario.
I kinda consider this a hack until we can encapsulate all state into a new submodule, but it works. 🎉 
reviewer: @bcoe
=> fix: preserve top-level, reset-able state for execution of parse callback

README.md, lib/command.js, lib/usage.js, lib/validation.js, test/yargs.js, yargs.js
after discussion today, @nexdrew and I settled on what I think is a pretty clever extension to the `parse()` function, as a simple API extension that supports running yargs in headless mode (yargs with no terminal output).
----
A callback `fn` can optionally be provided as the second argument to `.parse()`.
If a callback is given, it will be invoked with three arguments:
1. `err`: populated if any validation errors raised while parsing.
2. `argv`: the parsed argv object.
3. `output`: any text that would have been output to the terminal, had a
callback not been provided.
```js
// providing the `fn` argument to `parse()` runs yargs in headless mode, this
// makes it easy to use yargs in contexts other than the CLI, e.g., writing
// a chat-bot.
yargs()
.command('lunch-train <restaurant> …
```
=> feat: reworking yargs API to make it easier to run in headless environments, e.g., Slack

test/yargs.js, yargs.js
* perf: addresses the performance issue @nexdrew noted, related to calling `reset()` more times than necessary.
* fix: we now freeze config-objects, allowing a new context to be passed to consecutive runs to `parse()`.
CC: @nexdrew
=> perf: remove one call to reset(), fix: freeze was not resetting config objects.

test/yargs.js, yargs.js
We were applying yargs' parser to the context object (finding aliases, etc.). Unfortunately, folks often want to pass in objects with cyclical relationships to the parser, e.g., `http.request` which makes the parser blow up quite spectacularly.
We now carve out an exception for the `parse()` context object, such that it doesn't run through yargs' parser.
@ceejbot @zkat
=> fix: stop applying parser to context object

CHANGELOG.md
See https://github.com/yargs/yargs/pull/582#issuecomment-254358648
=> Moved breaking change from "features" to "breaking" in v5 changelog

lib/command.js, yargs.js
This is my preferred alternative to resetting the `context`.
It works by removing any `files` that were added during the execution of a command - e.g. if a command `builder` function calls `.commandDir()` itself - putting the `context` back into the state it was in before running the command builder and handler (with the exception of the `resets` count, which is desired).
This is consistent with the treatment of `context.commands` and with expectations of maintaining command execution scope. In other words, I should have done this from the beginning.
reviewer: @bcoe
=> fix(command): splice context.files when popping context.commands

lib/command.js, test/fixtures/cmddir/deep/within-a-dream.js, test/yargs.js, yargs.js
This addresses an issue @ceejbot ran into using headless `.parse()` in conjunction with nested sub-commands.
CC: @nexdrew
=> fix: context must be reset, or nested sub-commands fail on second invocation

README.md, lib/usage.js, test/usage.js
This is needed to display a complete help message for a command that failed in a top-level `fail` handler
=> Also pass yargs to the fail handler

yargs.js
For yargs' purposes, we do not need package information normalized (this involves checking license strings, applying semver, etc). The normalize step is also a fairly expensive operation.
=> perf: normalizing package data is an expensive operation

package.json, test/command.js, test/usage.js, test/yargs.js, yargs.js
I see no reason for us to not still call freeze()/unfreeze() to put yargs back into an initial state when `parse()` is called in isolation.
=> fix: still freeze/unfreeze if parse() is called in isolation

lib/validation.js, test/validation.js, yargs.js
Fixes a bug introduced with #556, demonstrated by https://github.com/laggingreflex/yargs-test-720.
Also, while investigating changes from 556, I found that validation logic for the `.implies()` method interprets a prefix of `--no-` on a key as a tiny DSL for "when this key is _not_ given". From this, we can actually ignore the `boolean-negation: false` setting for the `.implies()` method because `boolean-negation` affects _parsing_ but not the _DSL of implications_. To demonstrate this, I added some tests (with comments) showing how the DSL is interpreted.
The following use-cases are supported for `.implies()`:
1. `bar: 'foo'` = use of `--bar` requires that `--foo` be given
2. `bar: '--no-foo'` = use of `--bar` requires that `--foo` *cannot* be given
3. `bar: 'noFoo'` = use of `--bar` …
=> fix: do not use cwd when resolving package.json for yargs parsing config

README.md, lib/command.js, test/command.js
When migrating one of npm, Inc's internal chat-bots to yargs, I ran into some help strings that were documented like so:
`delete <user|org>    delete a user or organization`
Given that it's not a huge amount of work, I thought it would be worth adding this syntax to yargs' command API, in the form of positional argument aliases.
CC: @ceejbot, @nexdrew
=> feat: support for positional argument aliases

README.md, lib/usage.js, lib/validation.js, test/usage.js, test/validation.js, test/yargs.js, yargs.js
Getting @lrlna's wonderful work on splitting `demand()` into `demandCommand()`/`demandOption()` over the finish line.
Everything is %99 of the way there, just addressing some final nits from @maxrimue and myself -- excited to try to get yargs down to a few less open issue.
TODO:
fixes #504, #431 follow up with #618
=> feat: split demand() into demandCommand()/demandOption()

lib/usage.js, package.json, test/usage.js, yargs.js
I was able to remove the dependency `window-size` and instead use `process.stdout.columns` which effectively does the same thing but seems to be much less resource hungry.
=> refactor: use process.stdout.columns instead of dep

test/validation.js, yargs.js
@kumar303 pointed out a regression we accidentally introduced, in the process of reworking the command logic.
@kumar303, thanks for appreciating the nice CHANGELOG, we owe it to the [standard-version](https://github.com/conventional-changelog/standard-version) project which grew out of @nexdrew and my work at npm and on yargs.
=> fix: address min/max validation message regression

lib/usage.js, test/usage.js
This PR fixes #697. Now, if an example is defined without a description, the usage example will take up the entire line instead of just 50% of it.
=> fix: line wrapping for examples without desc

README.md, test/validation.js, yargs.js
=> Add option shorthand for conflicts / implies

.gitignore, lib/completion.js, lib/usage.js, lib/yerror.js, test/completion.js, test/usage.js, yargs.js
BREAKING CHANGE: yargs will no longer aggressively supress errors, allowing errors that are not generated internally to bubble.
CC: @iarna, @satazor curious as to what you think of this implementation.
=> feat: introduce custom yargs error object

lib/argsert.js, lib/command.js, lib/usage.js, lib/validation.js, test/argsert.js, yargs.js
Too help folks consuming the yargs API to better understand when they've provided illegal arguments to functions, this pull request introduces an approach to function argument validation.
I think this is a pretty clean API, and would potentially like to release it post-hoc as a library.
=> feat: function argument validation

README.md, yargs.js
Replaces `demand` in examples with `demandOption`. Closes #771.
=> docs: remove demand examples

lib/command.js, lib/validation.js, test/command.js, yargs.js
this addresses a bug related to positional command arguments in strict mode:
`command <foo> [bar]`
@nexdrew does this solve the issues that you brought up in slack?
=> fix: address positional argument strict() bug introduced in #766

test/yargs.js, yargs.js
BREAKING CHANGE: context now takes precedence over argv
----
context object should take precedence over parsed values in argv.
fixes: #724 
CC: @scriptdaemon I think this is better behavior for writing chat-bots using yargs.
=> fix: context should override parsed argv

package.json
BREAKING CHANGE: environment variables now take precedence over config files.
fixes: #627 
CC: @addaleax, @jaridmargolin
=> fix: pull in yargs-parser with modified env precedence

lib/apply-extends.js
issue from #779 
path.isAbsolute() not supported in node 0.10
use path.resolve() instead as mentioned in discussion in issue
=> fix: extending config files breaks on node 0.10

lib/validation.js, test/validation.js, yargs.js
strict mode now recognizes everything set in the `context` object sent to `parse()`.
fixes #791
=> fix: context variables are now recognized in strict() mode

test/command.js, yargs.js
there was a bug that caused an exception to be raised when `parse()` was called multiple times on the same yargs instance if `help()` is enabled.
fixes #776
=> fix: running parse() multiple failed when help() enabled

lib/command.js, test/command.js, yargs.js
fixes: #794 
@lhecker thanks for the bug report, if you have a second would love for you to test out this fix; we'll have it released to `npm cache clear; npm i yargs@next` in an hour or so.
=> fix: errors were not bubbling appropriately from sub-commands to top-level

README.md, lib/command.js, lib/usage.js, test/command.js, yargs.js
@nexdrew's work on introducing default command support.
_Why this is cool:_
1. it allows you to use the same flow control logic for top-level execution of yargs, as is applied to sub-commands.
2. tons of people have asked for it.
_todo:_
=> introduce support for default commands

.editorconfig, lib/command.js, test/command.js, yargs.js
fixes: #795 
positional arguments in sub-commands aren't white-listed for `strict()`.
=> fix: positional arguments of sub-command

README.md
Just update the README/docs to reflect the new order.
See yargs/yargs-parser#81 and #787
=> docs: env vars now take precedence over config file/objects

test/usage.js, yargs.js
Fixes #803, see discussion there.
First wrote the failing test, then included the fix.
=> fix: --help with default command should print top-level help

lib/validation.js, test/command.js
yikes, because we populate placeholder keys for arguments it broke `demand` logic in commands.
=> fix: populating placeholder arguments broke validation

test/yargs.js
There was 1 unit test that were failing with node-chakracore because of error message difference between v8 and chakracore. Added logic to generate error on fly and use that to compare the error message.
Ref: nodejs/node-chakracore#189
=> test: Made unit test passing with node-chakracore

test/command.js, yargs.js
casting argv._ elements back to string when evaluating for commands to
allow non-string commands to be correctly found and matched
Resolves https://github.com/yargs/yargs/issues/824
=> Number commands don't work

yargs.js
Run in non-interactive mode:
```javascript
yargs.wrap(yargs.terminalWidth())
```
Raises:
```javascript
YError: Invalid first argument. Expected number or null but received undefined.
at argumentTypeError (/Users/vitaly/Work/n/node_modules/yargs/lib/argsert.js:70:9)
at /Users/vitaly/Work/n/node_modules/yargs/lib/argsert.js:41:39
at Array.forEach (native)
at module.exports (/Users/vitaly/Work/n/node_modules/yargs/lib/argsert.js:35:21)
at Object.Yargs.self.wrap (/Users/vitaly/Work/n/node_modules/yargs/yargs.js:692:5)
at Object.<anonymous> (/Users/vitaly/Work/n/tools/cli.js:275:6)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
```
Because `process.stdout.columns` is `undefined` in …
=> Fix get terminalWidth in non interactive mode

test/yargs.js, yargs.js
we were accidentally printing the help text twice, if recommendations were made and `exit = false`.
```bash
Commands:
goat
Options:
--help  Show help                                                                        [boolean]
Did you mean goat?
Commands:
goat
Options:
--help  Show help                                                                        [boolean]
```
Let's not do this, it looks weird!
fixes #822
=> fix: we shouldn't output help if we've printed a prior help-like message

README.md, test/command.js, test/yargs.js, yargs.js
This adds a second argument to `strict` to disable it for a command.
=> Allow command to override global strict

.travis.yml, appveyor.yml, lib/command.js, test/command.js
#861 turned out to be due to an edge-case when using inner-commands with no handler; a reasonable fix seems to be to simply default handlers to a noop function when no handler is provided.
fixes #861
=> fix: positional arguments now work if no handler is provided to inner command

README.md, lib/apply-extends.js, package.json, test/fixtures/extends/packageA/package.json, test/fixtures/extends/packageB/index.json, test/fixtures/extends/packageB/package.json, test/yargs.js, yargs.js
Rather than adding more configuration for the `extends` feature, I've opted to simplify our logic somewhat:
it's now always assumed that either:
* extends, regardless of whether it comes in through `pkgConf` or `config`, points to the absolute path of a configuration file -- this approach might not solve 100% of use-cases, but I like how much it simplifies the problem.
* extends may now also represent the name of a module to require  (this assumes that the module exports configuration in its index, see https://www.npmjs.com/package/yargs-test-extends) -- _I think this feature allows users to build something resembling babel-presets on top of yargs!_
`BREAKING CHANGE: extends functionality now always loads the JSON provided, rather than reading from a specific key`
@rcoy-v great work on …
=> feat: allow extends to load configuration from a module

README.md, lib/validation.js, package.json, test/yargs.js
BREAKING CHANGE: environment variables will now override config files, '--' is now populated rather than '_' when parsing is stopped.
=> chore: upgrade yargs-parser

CHANGELOG.md, README.md, package.json, test/yargs.js
we can upgrade a ton of dependencies now that we require Node 4.
NOTE: we've reverted one of the breaking changes that was planned for `8.x`, based on a discussion at work today.
=> chore: upgrade dependencies

lib/validation.js, test/validation.js
made a couple slight tweaks to @dogboydog's work in https://github.com/yargs/yargs/pull/905
👋 @dogboydog thanks for the great work in #905, I just made a couple small tweaks to the tests and made it so we check for `undefined` rather than any `falsy` value, this way a conflicting key can be set to `false` and it will still trigger the conflict check.
fixes #899
=> fix: defaulting keys to 'undefined' interfered with conflicting key logic

lib/validation.js, test/validation.js, yargs.js
similar to #899, populating keys with `undefined` resulted in it being impossible to have optional `choices`.
fixes #849
=> fix: 'undefined' default value for choices resulted in validation failing

docs/api.md
=> docs: switch to absolute URL for commands docs

README.md, docs/api.md, lib/usage.js, test/command.js, test/completion.js, test/usage.js, test/validation.js, test/yargs.js, yargs.js
Almost 100% of my applications written with yargs have this boilerplate:
```
const argv = require('yargs')
.help()
.version()
.argv
```
I figured, why the heck don't we just enable `.version` and `.help` by default? (probably should have done this years ago).
BREAKING CHANGE: version and help keys are now enabled by default, and show up in help output; the implicit help command can no longer be enabled/disabled independently from the help command itself (which can now be disabled).
=> feat: enable .help() and .version() by default

package.json
One of the breaking changes of `v8.0.0` was requiring node 4 This updates the `engine.node` field in `package.json` which had the wrong value of `>=0.10`
=> Change engine node version to >=4

docs/examples.md
correct some typos in examples.md
=> docs: correct typos in example.md

index.js, lib/apply-extends.js, lib/argsert.js, lib/command.js, lib/completion.js, lib/levenshtein.js, lib/obj-filter.js, lib/usage.js, lib/validation.js, lib/yerror.js, test/argsert.js, test/before.js, test/command.js, test/completion.js, test/helpers/utils.js, test/integration.js, test/usage.js, test/validation.js, test/yargs.js, yargs.js
* Add `'use strict'` directive in source and test files. Here's why:
```
λ node --version
v4.0.0
λ echo let a = 1 > test-node4.js
λ node test-node4.js
E:\Projects\experiments\test-node4.js:1
(function (exports, require, module, __filename, __dirname) { let a = 1
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:413:25)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:475:10)
at startup (node.js:117:18)
at node.js:951:3
``` 
* Use arrow functions for callbacks and simple functions(`() => someval`). See below for caveats.
* Use `const`/`let` …
=> refactor: ES6ify

yargs.js
TypeScript requires the usage of undefined instead of null - this update allows both.
=> Updated yargs.js to allow both undefined and nulls

docs/api.md, test/yargs.js, yargs.js
I showed the the [proposed promise API](https://github.com/yargs/yargs/pull/940) for yargs to several coworkers today at npm, and they managed to talk me out of it. Their reasoning being:
1. yargs is for the most part a synchronous API, and they didn't see much value in introducing the deferred behavior.
2. my coworker @zkat felt that the method name `.then()` felt weird; _this method name should be used internally by the Promise api, not by APIs exposing a promise._
Rather than introducing a new method `run()` (or the method I recommended `then()` for exposing a Promise), I feel a good compromise is to instead extend the method `parse()` which already exists in the API. Calling:
```js
.option('x', {describe: 'x option'})
.parse()
```
is now possible, and is equivalent …
=> feat: allow parse with no arguments as alias for yargs.argv

lib/validation.js, test/validation.js
Address a bug @satazor found related to `strict()` mode firing for hidden options -- in the process I cleaned up strict mode logic for options a bit ... it seems like simply looking at the `aliases` map covers most of our bases.
fixes #948
=> fix: strict mode should not fail for hidden options

test/command.js, yargs.js
This ensures that the default command is executed even if the default command
is the only command that is defined.
=> Run default cmd even if it is the only defined cmd

.gitignore, docs/advanced.md, docs/api.md, lib/command.js, lib/usage.js, package.json, test/command.js, test/usage.js, test/yargs.js, yargs.js
Introduces the `.positional()` method, which makes positional arguments fully configurable (but wait there's more, positional arguments will also be included separately in help output):
TODO:
see: #541, #570, #959, etc
cc: @tkarls, @hax, @sloanlance, @iarna, etc.
=> feat: make positional arguments fully configurable

package.json, yargs.js
`read-pkg-up` has a dependency on [WTFPL](https://github.com/sindresorhus/parse-json/pull/12), which causes licensing issues for npm/Node.js.
`find-up` does pretty much what we need, so I don't see any reason to not simply switch to using it directly CC: @zkat.
=> chore: switch to find-up from read-pkg-up

test/command.js, test/yargs.js, yargs.js
Now that yargs is being used to build chat bots in a few places, the eager help command feels like more of a hinderance than a _help_; It's relatively rare that help ends a sentence, but it's fairly frequent for help to show up somewhere in a natural language string (triggering help output in a chat bot).
This is a breaking change:
* we no longer allow a single character help command to trigger help output.
* a help command must now be at the end of a sequence of commands to trigger output.
fixes #676
BREAKING CHANGE: help command now only works if it's the las command in a list.
CC: @zkat
=> fix: less eager help command execution

test/usage.js, yargs.js
Options with `description: false` will now show up help
fixes #851
=> fix: show hidden options in help

lib/usage.js, test/command.js, test/usage.js, test/validation.js, test/yargs.js
This PR changes the behavior of the `$0` token (when used within the contents of the `usage`, `epilog` and/or `example` methods), so that it displays the executing file's basename, as opposed to the full path. This has the affect of providing default help text that is closer to what the end-user would actually run, since they would likely be running the CLI on their path (or via an `package.json` script), as opposed to using the CLI's entrypoint script path.
This is a breaking change, but since #975 introduces a breaking change for the `usage` method, I figured I'd put this PR out for discussion's sake. I updated all of the tests to ensure they still pass, but there may be other scenarios that this change would break, so I'd love some feedback.
I'm also not entirely sure this is the right …
=> [Discussion] Replacing "$0" with the executing file's base name

locales/en.json, locales/ko.json, locales/pt_BR.json
Sorry for mentioning so many folks. 
I've been undertaking an overhaul of the `.command()` and `.usage()` API (introducing the concept of [`.positional()`](https://github.com/yargs/yargs/blob/f5bc44c66278c28404552c7b292a8f8f53ca4f29/docs/api.md#positionalkey-opt)).
In the process I've introduced a couple more words to the English language file:
```json
{
"Positionals:": "Positionals:",
"command": "command"
}
```
I would love help updating the files for each languages to reflect these new terms.
_... I would also love help testing the new features..._
Given that `yargs@10` represents a pretty large update to the command API, I would also love help testing. The new features are documented here:
https://github.com/yargs/yargs/blob/f5bc44c66278c28404552c7b292a8f8f53ca4f29/docs/api.md#usagemess …
=> chore: new translations for command API overhaul

lib/command.js
converting the positional commands being parsed to a string resulted in some edge-cases when parsing positional arguments of the form "Foo Bar".
=> fix: parse array rather than string, so that quotes are safe

docs/api.md
We should mention that multiple array arguments are all flattened.
=> document multiple array arguments

docs/advanced.md, lib/command.js, package.json, test/yargs.js, yargs.js
OK this is a very WIP and ugly first draft of the middleware feature.
I will need some help to change passing the middleware using a chaining function instead of an array.
For more context check https://github.com/yargs/yargs/issues/876
@bcoe I would love to get some feedback from you.
TODO :
=> feat: middleware

locales/nn.json
I've added translations for Nynorsk, which is the other official written standard for the Norwegian language. I've based it off the Bokmål translations, so the terminology *should* be consistent.
=> Add Norwegian Nynorsk translations

test/yargs.js
Hello,
We have encountered what appears to be a bug in handling positionals of type string. As you can see from the failed test, yargs is parsing the example as a boolean.
We are unsure if this is a bug or if we are doing someting wrong.
We are happy to provide a fix, if you can confirm this is a bug.
=> Add failing test for using positional

docs/api.md, lib/command.js, lib/usage.js, test/command.js
Addresses issue #510 ~~"Allow command handler to accept a promise"~~ "Support async (i.e. promise-returning) command handlers"
> we'd just need to update the argument validation and invocation of a command handler to understand a promise
This PR handles "update [...] invocation of a command handler to understand a promise". Nothing is done if the promise resolves, but if it rejects, it is handled as ["failure"](https://github.com/zenflow/yargs/blob/master/docs/api.md#failfn) with an `err` but no `msg`.
@bcoe Not sure what needs to be done about "update the argument validation"... It seems like there's no change needed; arguments to command handlers, and validation of said arguments, aren't affected by this feature. This feature deals only with what is *returned* by the command handler (a …
=> Async command handlers

package.json, test/command.js
This fix is required to package chai for Debian.
From a Debian packager:
> (...) in debian, we want to use a single version of chai for all
modules we ship and some modules need chai 4. So we need to port all
modules still using chai < 4 to chain 4.x.
I've updated the tests accordingly, and tested for stylistic differences. Please let me know if anything else is to be done!
=> Use chai 4.x

lib/validation.js, test/validation.js, yargs.js
This fixes the underlying issue in #1015 _without_ breaking nested commands. This PR is built on top of #1049.
=> fix: Set implicit nargs=1 when type=number requiresArg=true

lib/validation.js, package.json, test/usage.js, test/validation.js, test/yargs.js, yargs.js
BREAKING CHANGE: requiresArg now has significantly different error output, matching nargs.
based on @evocateur's clever suggestion, `requiresArg` is now just an alias for `nargs(1)`; simplifying the implementation significantly and moving behavior closer to the parser.
=> feat: requiresArg is now simply an alias for nargs(1)

lib/apply-extends.js, package.json, test/fixtures/no-extension, test/fixtures/no-require-main.js, test/integration.js, test/yargs.js, yargs.js
So, it turns out Jest overrides the module-local `require` and neglects to assign `require.main.filename` (https://github.com/facebook/jest/issues/2150). Maybe I'll even get around to fixing it [here](https://github.com/facebook/jest/blob/be66ccc26ea80e825f2fb4f0f21433832a2c4d97/packages/jest-runtime/src/index.js#L675-L689), but in the meantime, we can work around it by avoiding the "extra" `path.dirname()` when it isn't neccessary (because `require-main-filename` defaults to `process.cwd()`).
Also, I changed a bunch of function parameters to avoid shadowing `path`, it was extremely confusing (and ridiculous to have an inner `require('path').dirname` when `const path = require('path')` is already present at the top of the file).
=> fix: choose correct config directory when require.main does not exist

lib/apply-extends.js, test/fixtures/extends/.myotherrc, test/fixtures/extends/.myrc, test/yargs.js
fixes #1035 
This simply updates the regex to include *.*rc files. It does not handle the situation with rc files that are formatted in INI format. That seems to be a separate discussion.
=> extend *.rc files in addition to json

example/cmds/init.js, example/cmds/remote.js, example/cmds/remote_cmds/add.js, example/cmds/remote_cmds/prune.js, example/command_hierarchy.js
Add the command hierarchy example from the [advanced topics documentation]
to the actual examples.
[advanced topics documentation]: docs/advanced.md
=> docs(example): add command hierarchy example

docs/api.md, lib/usage.js, test/usage.js, test/yargs.js, yargs.js
Adds a `--show-hidden` flag to show options defined with `hidden: true` property
Recap: (#962) Earlier, a fix was made to address the issue where `.options({...})` without a `description` property did not show up up in `--help`. The fix introduced a new `hidden: true` property to truly hide an option from `--help`, and to show all other options (even without `description` property)
Issue with the fix: There was no way to show options defined with `hidden:true` property (they were hidden permanently)
Solution (this patch): This introduces a new flag: `--show-hidden` (pre-configured) which can be used to show those hidden options.
The default key for this new flag may also be custom configured with a new function property `.showHidden('custom-show-hidden')`
=> feat: --show-hidden

lib/usage.js, test/command.js, test/usage.js, test/validation.js, test/yargs.js
- e5deaf7 Add tests
- b07abdc Remove the trailing white spaces from the help output
- 6a13023 Print a new line between the help and the error on fail if showHelpOnFail is enabled
=> Remove the trailing white spaces from the help output

package.json
BREAKING CHANGE: yargs-parser does not populate 'false' when boolean flag is not passed
=> chore: 'false' value is no longer set when boolean flag is not passed

appveyor.yml, docs/api.md, lib/command.js, lib/middleware.js, test/middleware.js, yargs.js
PR-AN-03: Update API readme.
PR-AN-01: Fix tests.
PR-AN-01: Remove param defaults for Node 4 comp.
PR-AN-01: Remove spread operator for Node 4 comp.
PR-AN-01: Add unit tests for middleware.
PR-AN-01: Bind this to middleware for chaining.
=> PR-AN-01: Global Middleware feature.

test/usage.js
I found this randomly, it was harshing my code-folding mellow...
=> format: avoid weird newlines before closing paren

docs/api.md
Fixed a likely copy/paste mistake.
=> docs: Restore correct header order

docs/api.md
The completion function checks that the number of arguments is less than 3 before performing the logic that resolves a promise, so passing `done` here will cause the promise to not resolve.
=> docs: Use correct completion callback signature

package.json
All v4 of y18n does is drop support for 0.10 and 0.12.  Kept a broad range (3 & 4) to make it easier to dedupe trees.
=> chore: Allow v4 of y18n

package.json
Static analysis should be done before tests. It saves times and also lints and catches errors through static analysis in tests.
It could also be moved to the test script, before nyc.
=> chore: Run standard in pretest lifecycle

example/help.js
The name of the flag: `version` and the actual version value: `1.0.1` were switched.
=> Corrected version specifier in help example

test/yargs.js, yargs.js
Fix #1071
Do no add `undefined` properties in parsed result object for options absent from provided `argv`.
BREAKING CHANGE: Options absent from `argv` (not set via CLI argument) are now absent from the parsed result object rather tahn being set with `undefined`
=> feat: remove `setPlaceholderKeys`

CHANGELOG.md
Earlier in the changelog for 12.0.0 it mentions that Node 6 was _added_ to the testing matrix, then under breaking changes it says the opposite. I _believe_ that the breaking change section intended to say that Node 4 was dropped (it is EOL after all) not Node 6.
This will also need to be updated in the GitHub release (which is used by tolls like greenkeeper / renovate / dependabot/ etc).
=> Fix breaking change note in CHANGELOG.md

package.json
The only breaking changes is that support for Node.js 4.x is dropped. Since Yargs currently only supports Node >= 6 this shouldn't be a problem.
=> Bump decamelize & find-up

package.json
This change was mentioned in the release notes for 12.0.0, so it shouldn't be a breaking change...
=> Bump engines to Node.js 6.x

lib/command.js, test/middleware.js
=> I-1178: Middleware fix

docs/advanced.md
=> docs(advanced): fix typo

package.json
I noticed the package install size creeping up quite a bit in the last versions: https://packagephobia.now.sh/result?p=yargs
After taking a look at it a big cause is the `decamelize` dependency, replacing it with `kebab-case` decreases the package install size from around 1400 kB to 670 kB.
=> Downgrade decamelize dependency to 1.2.0 to decrease package size

lib/usage.js, test/usage.js
```js
.options({
foo: {
describe: 'FOO',
group: 'Hidden',
hidden: true
},
baz: {
describe: 'BAZ',
group: 'Hidden',
hidden: true
}
})
.help()
.argv
```
Before:
```bash
Hidden
--foo  FOO
--baz  BAZ
Options:
--version  Show version number                                       [boolean]
--help     Show help                                                 [boolean]
```
After:
```bash
Options:
--version  Show version number                                       [boolean]
--help     Show help                                                 [boolean]
```
=> fix: hide `hidden` options from help output even if they are in a group

locales/nb.json
This is a continuation of #1207, as I noticed it had the same grammatical mistake.
=> Improve Norwegian Bokmål translations

yargs.js
Default behavior of yargs is to take the first two args of process.argv
to put into $0 as this is usually the program to execute a script
e.g. 'node app.js' but for bundled electron apps this results in $0
being populated with not only the executing program but also the first
parameter. This fix modifies the check for node/iojs (and adds electron)
so in case of those 3, the executing program is skipped in $0 as it was
before, but in case where a bundled app is executed, the first parameter
is skipped.
This is only a cosmetic change for proper help printouts which use $0
A manual `yargs.parse(process.argv.slice(1))` is still necessary for
electron not to skip the first parameter, during parsing
=> fix: $0 contains first arg on bundled electron app; fixes #685

test/usage.js
Issue #1130 seemed to already be fixed. This is just to add a regression test to make sure it stays working.
=> Add regression test for hidden options with default values

docs/advanced.md, docs/api.md
This adds the documentation for the non-singleton interface (as described at https://github.com/yargs/yargs/blob/a40cbc9/index.js#L4) to the markdown docs, and the `.parsed` and `.exit()` interfaces, which are useful in non-singleton usage. In particular, I noticed that they are used in [lerna](https://lernajs.io/)'s command line parsing.
=> docs(advanced): document non-singleton use, .exit() and parsed

yargs.js
While exploring yargs I discovered an edge-case error.
`_runValidation` assumes that `parseErrors` is an `Error` object with a `message` property. However, it's legitimate in JavaScript to `throw` arbitrary object. When that object is not an `Error`, it's most commonly a `String`, i.e.: 
throw 'This is an error.'
See: https://jsfiddle.net/softcraft/gxka09nb/
When `_runValidation` feeds `parseErrors.message` to `YError`, it's `undefined`, and thus `YError` generates an error message with the (quite unhelpful) 'yargs error' string, not the value of `parseErrors`. 
This change will allow `_runValidation` to use the value of `parseErrors` as a fallback if `parseErrors.message` doesn't exist. This allows `throw "error!"` to work successfully. 
(I encountered this problem by throwing a String …
=> fix(validation): Use the error as a message when none exists otherwise

docs/examples.md
The help example using line_count.js was no longer accurate according to actual results. From what I can tell this was changed in #983 according to #1010.
=> Edited help example to align with actual output

completion.sh.hbs
Hey,
it seems that if a command is not found, the fallback file autocompletion does not work the same as the standard bash autocompletion:
**CURRENT**
`some-cmd folder-na(tab)` -> `some-cmd folder-name `
currently the folder name is inserted, including a space at the end
**PROPOSED**
`some-cmd folder-na(tab)` -> `some-cmd folder-name/`
In the current bash versions the folder name is inserted with a slash at the end, allowing you to chain folder paths
With this change bash will decide how to handle the autocompletion.
MacOS 10.14
https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html
https://stackoverflow.com/a/22827323
=> Consistent bash-completion if a command is not found

docs/api.md, test/fixtures/configured-bin.js, test/integration.js, test/yargs.js, yargs.js
A non-breaking proposal to address #1259 and #1248, it might be incomplete so please amend if needed.
=> feat: Add `.parserConfiguration()` method, deprecating package.json config

.travis.yml
Would have waited until April, but CI is having build failures on 6; motivating me to drop support early.
BREAKING CHANGE: dropping Node 6 which hits end of life in April
=> chore: drop Node 6 from testing matrix

package.json, test/command.js
see: #1099, #550
BREAKING CHANGE: options with leading '+' or '0' now parse as strings
=> feat: options/positionals with leading '+' and '0' no longer parse as numbers

docs/api.md, lib/argsert.js, lib/command.js, lib/middleware.js, test/middleware.js, yargs.js
This makes a few changes to #1255, based on conversations with @trevorlinton, @evocateur, and a few other folks.
main differences:
* `applyBeforeValidation` now works on a per-command basis (to do so call `.middleware` in a builder function).
* the `yargs` object is now populated as a second parameter to middleware (I intend to in a separate pull request, add the ability to get the current aliases available).
@Khaledgarbaya it's my feeling that this simplifies things a bit, and makes the `applyBeforeValidation` work in the more general case ... making me an advocate.
TODO:
=> chore: some slight modifications to applyBeforeValidation based on conversations

.travis.yml, CHANGELOG.md, test/middleware.js
for the benefit of mocha, holding off on decision to drop Node 6 support @boneskull @plroebuck.
=> chore: forgoing decision to drop Node 6 until April

docs/api.md, locales/nl.json
- "Commands:" and "command" should be translated consistently (it was "Opdrachten:" and "commando"); "commando" is much more appropriate in this context than "opdracht"
- In Dutch, there is a difference between "nummer" and "getal". A "nummer" is used for the English "digit" ([0-9]). A "getal" is what is meant here (the type of all numbers)
- the translation of "boolean" is "booleaans"
- "string" was translated as "text". "text" is not a Dutch word. In Dutch, "text" becomes "tekst". But a string is not a text.
https://www.microsoft.com/en-us/language/Search?&searchTerm=number&langID=Dutch&Source=true&productid=All%20Products translates "string" to "tekenreeks", but that is
hypercorrect. Nobody uses that term. In Dutch, we just use the English term "string" colloquially.
- "Non-option …
=> Make Dutch translation consistent, fix Dutch language errors, and make it real Dutch

test/yargs.js
The default for Node.js's `util.inspect` `compact` option might soon
change to `3` which slightly changes the default output for objects.
This change accepts both formats so that the test passes in all Node.js
versions.
Refs: https://github.com/nodejs/node/pull/27109
=> test: accept differently formatted output

CHANGELOG.md
In https://github.com/yargs/yargs/commit/4375680c83e76cbf5cfedbfd81c138ce45b90b54, changelog of v13.2.0 was replaced with v13.2.1.
=> docs: restore removed changelog of v13.2.0

docs/api.md
Hi all,
I bumped into #1307 while working on another yargs based project and found myself wondering what the `--no-`prefix did.  I went to the yargs docs, found the api reference and tried searching in there but couldn't find anything.  I ended up searching with github's project search to find what I was after.
So this change is quite simple, make mention of the `--no` boolean prefix on the api doc page and link to the existing doc under parsing tricks.  Hopefully that should make it a little quicker to find.
=> doc: make `--no-` boolean prefix easier to find in the docs

locales/de.json, locales/en.json, locales/fr.json, locales/it.json, locales/nl.json, test/validation.js, test/yargs.js
The word "implications" is extremely confusing here. It is only people who know the Yargs API that understand that these are the dependencies created by the `implies()` method.
Users of the CLI have no idea what we are talking about.
This changes the label of the concept to "required argument dependencies".
This string is used in the code as the prelude to a list of "implications" that have failed, not a warning. The earlier form was more an expression of a warning. The new form is more an expression of a title of a list.
=> Change the label for "Implications failed:" in English

docs/api.md, test/usage.js, test/yargs.js, yargs.js
**Summary**
Add `defaultDescription` to `supportedOpts` for positional arguments.
Fixes #1241
=> feat: support defaultDescription for positional arguments

package.json, test/validation.js, test/yargs.js, yargs.js
This eliminates half the dependencies of yargs without any change in
functionality.  The extra dependencies were used by the os-locale module
to execute detection utilities, this execution functionality was always
disabled by yargs.
Fixes #1354
=> feat: Inline code to detect current locale from environment

lib/validation.js, test/validation.js
The test was disabled for commandless yargs, but as the validation is done on the innermost yargs, it was always disabled.
Closes #1313
=> fix!: do not allow additional positionals in strict mode

docs/api.md
tiny fix to a Markdown syntax snafu
=> docs: fix emphasis of note to .parserConfiguration

index.js, test/yargs.js
`singletonify()` used to set `Argv`'s properties to `inst`'s properties values _at the time of `Argv`'s last call_.
So `Argv`'s properties and the `inst`'s ones could diverge afterwards, such as `parsed` after a call to `parse()`, still being `false` in `Argv.parsed`, not in `inst.parse`.
`singletonify()` now adds setters to `Argv` instead, looking for the value of the corresponding property in `inst` _at the time the property is used_.
=> fix: properties accessed on singleton now reflect current state of instance

lib/apply-extends.js, test/yargs.js
=> fix: tolerate null prototype for config objects with `extends`

lib/command.js, lib/usage.js, lib/validation.js, test/yargs.js, yargs.js
Extends the freezing/unfreezing mechanism already in place for `parse(args, cb)` to `parse()` (without arguments) to be able to call it several times with the same behavior.
Also corrects the builder function return value handler for it no longer to depend on `yargs.parsed` being set after a call to `parse()` (which is no longer the case after unfreezing).
Closes #1137
=> fix: calling parse multiple times now appropriately maintains state (#1137)

index.js, test/yargs.js, yargs.js
BREAKING CHANGE: we now only officially support yargs.$0 parameter and discourage direct access to yargs.parsed
https://github.com/yargs/yargs/pull/1369 and https://github.com/yargs/yargs/pull/1366 are incompatible, because `1369` unfreezes properties before returning (at which point yargs.parsed is the original value of `false`).
I would like to discourage users from accessing these properties on yargs, I've added a hack to make behavior the same as before, but now warn when `yargs.parsed` is accessed in singleton mode.
=> fix! yargs.parsed now populated before returning, when yargs.parse() called with no args

lib/usage.js, test/usage.js, yargs.js
We have a central script (`./tvui`) in the root of our repository that is used to manage everything. It is executed directly, not through `yarn` or `npm-scripts`.
Using `yargs.scriptName('./tvui')` results in just `tvui` being shown in all of the commands/examples. This seems to happen due to the `path.basename` call in [`lib/usage.js#154`](https://github.com/yargs/yargs/blob/e3981fd3a5f65427b4d8daae7331f956c4d2d70d/lib/usage.js#L154).
Track that the script name was set using the `scriptName` function and don't perform a `path.basename` on it.
=> Don't alter the user supplied script name

lib/usage.js, test/usage.js
We wrap our commands in a function that adds `docs`, `maintainer`, and `slack` properties to the command module object. We use these properties as part of an automatically generated epilog that we add to each command.
Currently subsequent calls to `epilog` will overwrite any previous epilog.
Store epilogs in an array which is added to on each `epilog` call. Join them with new lines when building usage.
=> Support multiple epilogs being added

test/completion.js, yargs.js
When using `showCompletionScript` the variable `completionCommand` is `null` resulting in a bad installation instruction. For example:
`yargs.showCompletionScript('/usr/local/bin/my-app');`
```shell
###-begin-my-app-completions-###
#
#
#
_yargs_completions()
{
local cur_word args type_list
cur_word="${COMP_WORDS[COMP_CWORD]}"
args=("${COMP_WORDS[@]}")
type_list=$(/usr/local/bin/my-app --get-yargs-completions "${args[@]}")
COMPREPLY=( $(compgen -W "${type_list}" -- ${cur_word}) )
if [ ${#COMPREPLY[@]} -eq 0 ]; then
COMPREPLY=()
fi
return 0
}
complete -o default -F _yargs_completions my-app
###-end-my-app-completions-###
```
Notice that `null` is printed for the command.
It's possible to set the `completionCommand` variable by calling `yargs.completion()` but this will also log the …
=> Allow completionCommand to be set via showCompletionScript

yargs.js
I tried to write a test case for this but couldn't find one that reproduced the issue. I _think_ the issue only exists when using `yargs` as a singleton. The issue is that two completion scripts are logged, one from the explicit call to `showCompletionScript` and the second from [`yargs.js#1108`](https://github.com/yargs/yargs/blob/9febcbe61be4098cbb112843b899e80d2a6bb35c/yargs.js#L1108).
=> Don't set stateful completionCommand in showCompletionScript

docs/advanced.md
Looks like somebody copied the parser options from `package.json` and accidentally copied a bit too much. Hope I can save the next guy the 15 minutes it took me to figure this out...
=> fix(docs): fix incorrect parserConfiguration documentation

docs/api.md
I believe this could be an oversight?
Source: [`.option()` calls](https://github.com/yargs/yargs/blob/07c8537aa727d3c9b026523ee255758d76939cb3/yargs.js#L611), [`.conflicts()`](https://github.com/yargs/yargs/blob/07c8537aa727d3c9b026523ee255758d76939cb3/yargs.js#L444), [`.implies()`](https://github.com/yargs/yargs/blob/07c8537aa727d3c9b026523ee255758d76939cb3/yargs.js#L438)
=> docs: update argument type descriptions of .options()

lib/completion.js
I don't run zsh as a login prompt, and I haven't `chsh`'d from bash to zsh, and so yargs was still giving me the bash completion when running it inside of zsh.
=> fix: detect zsh when zsh isnt run as a login prompt

docs/api.md
Add a note precising the output parameter of a parse() callback only contains text output by yargs internal logger.
Closes #1397
=> docs: precise parse() callback output parameter contents

docs/api.md
This fixes https://github.com/yargs/yargs/issues/1389 . The wording I feel is not so ideal. Maybe suggestions needed.
=> docs(api): add description for coerce behavior for array type argument

lib/validation.js, test/usage.js
=> Make strict() work with options containing hyphens

index.js, lib/command.js, lib/usage.js, test/command.js, yargs.js
This should address a couple minor issues that lead to #1144:
1. `self.parsed` was being populated with an `argv` instance rather than a `yargsParser.detailed` instance, leading to the missing fields that raised exceptions.
2. once `1.` was addressed, the help message was incorrect, because `async` handlers prior to this relied on state not being reset; to solve this, we now cache the help message that _would_ be displayed at the time of a promise's invocation.
3. there was one final issue related to our `self.parsed`, TypeScript executes all methods on a class, making our warning message display even though it wasn't explicitly invoked (I've reverted the warning message).
*TypeScript Issue:*
```js
var __importStar = (this && this.__importStar) || function (mod) {
if (mod && …
```
=> fix: populate correct value on yargs.parsed and stop warning on access

README.md
Proposal to remove "default: false" on verbose in the README.
I was mildly confused when I copied the example and called it with `-v`, expecting no value to default the value to true. However it appears as if the default value overrides both the "not passed" value, and the "passed with no value" parameter. This makes me believe "default: false" should never be used, as the default of default is effectively false.
At the very least I believe it shouldn't be part of the example in the README, especially on conjunction with the verbose parameter, which makes a program that uses verbose differently than any program I have ever seen.
=> Removed "default: false" on verbose.

docs/api.md, test/usage.js
This PR adds doc and test for an existing feature: Supplying a print callback to `usage.showHelp` instead of a `console` function name.
We use the callback in our code to explicitly specify the stdout/stderr stream dependencies of yargs - tests can use it instead of mocking the console.
Thanks for making this great library!
=> feat: formalize existing callback argument to showHelp

lib/is-promise.js, test/is-promise.js
I came across this problem when I was creating a CLI tool which uses [NodeGit](https://www.nodegit.org/) internally. NodeGit is using its own fork of es6 promises and so yargs failed to handle my async code because it didn't return an instance of `Promise`. But yargs should accept all promises as long as they are spec conform, regardless if its an native promise, a polyfill, a bluebird promise or any custom implementation.
So, I fixed the code to look for thenable objects instead of making an instanceof check.
=> Fix promise check to accept any spec conform object

lib/middleware.js, test/middleware.js
Closes #1335
Async middleware where called:
- once for the innermost subcommand (expected)
- then once for every parent of this subcommand (unexpected)
Due to an incorrect check in the first run of middleware (before validation).
CI will probably fail as #1411 introduced a broken test in master.
=> fix: #1335: async middleware called twice

test/usage.js, yargs.js
=> fix: groups were not being maintained for nested commands

CHANGELOG.md, package.json, test/yargs.js
introduces unknown-options-as-args feature, which allows unknown options to be treated as arguments (either being collected inside of `_`, or passed as values to proceeding options).
CC: @henderea, @mleguen, @kellyselden
=> feat(deps): introduce yargs-parser with support for unknown-options-as-args

docs/typescript.md
Importing using `import yargs from 'yargs';` prevents a warning log to console about the `parsed` property being dropped in a future major version.
In future major releases of yargs, "parsed" will be a private field. Use the return value of ".parse()" or ".argv" instead
Closes #1439
=> fix(docs): TypeScript import to prevent a future major release warning

README.md, docs/webpack.md
Usage example for webpack, both in javascript and typescript.
I stumbled myself on this issue in one of my projects a few days ago, and found it was about time to close #781 !
=> doc(webpack): webpack example

test/fixtures/configured-bin.js, test/fixtures/no-extension, test/fixtures/no-require-main.js, test/fixtures/normal-bin.js, test/fixtures/package.json, test/fixtures/symlink-bin.js, test/integration.js, test/yargs.js, yargs.js
removes deprecated feature, in prep for breaking release.
=> refactor!: remove package.json-based parserConfiguration

.travis.yml, yargs.js
Get back to tracking the Node.js release cycle a bit closer.
fixes #1438
=> chore!: drop Node 6 support

test/yargs.js
Failing test case for https://github.com/yargs/yargs-parser/issues/205.
If you change yargs-parser to v13.1.1, the test passes.
In use [here](https://github.com/CrowdStrike/faltest/blob/5403b37f6d527764eee5ae60988b1dbdd445d065/packages/cli/src/index.js#L90-L97)
=> missing array choice regression test

package.json
BREAKING CHANGE: yargs-parser@16.0.0 drops support for Node 6
=> fix!: update to yargs-parser with fix for array default values

test/obj-filter.js
This is a contribution to https://github.com/yargs/yargs/issues/1465
BEFORE
obj-filter.js           |      100 |       75 |    66.67 |      100 |              4,10 |
AFTER
obj-filter.js           |      100 |    88.89 |      100 |      100 |                10 |
=> test: cover missing filter arg in obj-filter

test/argsert.js
Contribution towards code coverage for #1465 
This gets `lib/argsert.js` to 100% coverage. Technically only one test increased coverage, but I think there is value in both tests as there wasn't actually coverage of any positions aside from first.
Before:
After:
=> Add tests for argsert warning to display positional information

lib/command.js, package.json, test/command.js, yargs.js
@evocateur I believe this addresses at least half of the issues you described in #1457 (it sounded like you were potentially describing two bugs).
mind trying the branch out?
fixes #1457
=> fix: -- (stop parse) was not being respected by commands

.github/release-please.yml
[release-please](https://github.com/googleapis/release-please) will now automatically tag GitHub releases when a [release PR](https://github.com/yargs/yargs/pull/1462) is merged.
=> build: switch to release-please for releases

test/yargs.js, yargs.js
see: https://github.com/babel/babel/pull/10733, #1482
=> fix: temporary fix for libraries that call Object.freeze()

lib/completion.js, test/completion.js, yargs.js
getCompletion() throws when completing an option, as it needs `parsed.aliases`, which is lost (unfreezed) when calling `.parse()` with arguments.
See #1434 
This is a side effect of fixing `.parse()` to be able to call it several times, a few months ago.
This PR provides `parsed` to completion before unfreezing it.
=> fix getCompletion() no longer working for options

docs/typescript.md
As stated in #1455 , the typescript example in the documentation is misleading, as the import syntax used (`import yargs`) only works when "esModuleInterop" is set to "true", which is not the default typescript configuration.
So this PR suggests both syntax, with the default syntax being the one working with the default typescript configuration (`import * as yargs`).
=> doc(typescript): suggest both import syntax

docs/advanced.md
The first two examples fail silently, except if  
.argv
is appended.
=> The first two examples fail silently

lib/usage.js, test/usage.js
To be coherent with what yargs/parser considers as an option single dash key, do not display '-1' but '--1' when '1' is used as an option key or an alias.
See #1454
=> fix: show 2 dashes on help for single digit option key or alias

docs/advanced.md, lib/command.js, test/yargs.js, yargs.js
=> feat: onFinishCommand handler

docs/advanced.md
Fixes typo 'comand' -> 'command'
On @mleguen petition: https://github.com/yargs/yargs/pull/1473#discussion_r353603365
=> Advanced docs typo 'comand'

docs/api.md
This fixes the anchor URLs for `.option` and `.command` in the API docs.
=> docs: fix bad urls in the API docs

lib/command.js, test/command.js
Positionals where no longer populated using `unknown-options-as-args`, as yargs turned them into options before handing them to yargs, but withoud declaring the corresponding option. So they were handled by yargs-parser as unknown options.
The "hidden" options for the positionals are now declared when using `unknown-options-as-args`.
Closes #1444.
=> fix: populate positionals when unknown-options-as-args is set

docs/typescript.md, docs/webpack.md
Fix typescript examples to use the right import syntax for a commonjs module such as yargs.
See explanation in typescript documentation [here](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require):
> Both CommonJS and AMD generally have the concept of an exports object which contains all exports from a module.
>
> [...]
>
> When exporting a module using export =, TypeScript-specific import module = require("module") must be used to import the module.
=> fix(docs): use recommended cjs import syntax for ts examples

lib/completion.js, test/completion.js
When the user did not already enter two dashes, and when the option is not a single digit one.
Closes #265
=> feat: complete short options with a single dash

contributing.md
This adds a short note to the contributing docs about how to contribute to the website since I had a hard time finding how to serve the docs locally.
=> docs: add link to website repo in contributing docs

lib/completion.js, test/completion.js
Closes #1431 
When boolean-negation is set:
- completes --no-flag when flag defaults to true
- avoids repeating flags whose negated counterpart is already present
=> feat(completion): takes negated flags into account when boolean-negation is set

docs/api.md, index.js, lib/process-argv.js, test/yargs.js, yargs.js
If process.defaultApp is false (for built electron app), remove only the first element of process.argv (the app binary) and not the two first elements (node + the app script).
See https://github.com/electron/electron/issues/4690#issuecomment-217435222 for mor info.
Solve part of #685
=> Use process.defaultApp to detect built electron app

lib/command.js, lib/usage.js, test/helpers/utils.js, test/usage.js
Close #1533 
After a call to `.parse()` for a command with an async handler, next calls to parse, if they need to display help, display help for this command.
=> fix: help always displayed for the first command parsed having an async handler

package.json
BREAKING CHANGE: yargs-parser@17.0.0 no longer implicitly creates arrays out of boolean
arguments when duplicates are provided
=> feat(deps)!: pull in yargs-parser@17.0.0

docs/api.md, lib/validation.js, test/validation.js, yargs.js
I have met your demands @boneskull 
This seemed like a reasonable feature request, and I'm excited to see whether you get use out of it.
Code review appreciated.
---
~BREAKING CHANGE: if you use `.demandCommand()` or `.demandCommand(1)`, in conjunction
with defining commands, `.strictCommands()` is enabled automatically.~
Since the breaking changes to `yargs-parser` were for undocumented behavior (and 15.x.x was actually a regression with regards to the parsing of booleans, I'm going to try to release 15.x.x as a non-breaking change; if the candidate release seems to be breaking too many folks, we can revisit this decision).
=> feat: introduces strictCommands() subset of strict mode

lib/process-argv.js, test/yargs.js
Fix the first attempt at detecting bundled electron apps, whose arguments start at `process.argv[1]`, not `process.argv[2]`, by handling `process.versions.electron` and `process.defaultApp`.
Fixes: #685
=> fix(yargs): correct support of bundled electron apps

package.json, test/yargs.js, yargs.js
In #1054, `requiresArg` was refactored to use a `nargs` of `1` to specify that a value was required following an option (`--x foo` is valid, `--x` is not valid).
The problem with this design decision  was that it created an ambiguity when `array` and `nargs` were used in conjunction, one could not distinguish between:
* an array that should only accept one value.
* an an array that required _at least_ one value.
This behavior lead to issues like https://github.com/yargs/yargs/issues/1570, https://github.com/yargs/yargs/issues/1098, and https://github.com/mochajs/mocha/pull/4196.
---
To solve this problem [`nargs` now accepts the special value `NaN`](https://github.com/yargs/yargs-parser/pull/251), this value is used by `requiresArg` to specify that an `array` accepts "one or more" values …
=> fix: address ambiguity between nargs of 1 and requiresArg

lib/usage.js, test/usage.js
Add proper usage output for the now supported single-digit boolean aliases which landed in yargs-parser.
ref: https://github.com/yargs/yargs-parser/pull/255
/cc @bcoe @mleguen 
relates to: #1493
=> feat: add usage for single-digit boolean aliases

README.md
adds back a coverage badge that's based on  `.nycrc` file, which enforces coverage thresholds.
=> docs: add back a coverage badge

.github/workflows/coverage.yaml
experimenting with continuing to run coveralls, but only when landing code to `master`.
=> build: continue running coveralls on master

package.json, test/yargs.js, yargs.js
* \_\_proto\_\_ will now be replaced with \_\_\_proto\_\_\_ in parse ([#258](https://www.github.com/yargs/yargs-parser/issues/258)), patching a potential 
prototype pollution vulnerability. This was reported by the Snyk Security Research Team.([63810ca](https://www.github.com/yargs/yargs-parser/commit/63810ca1ae1a24b08293a4d971e70e058c7a41e2))
=> fix: __proto__ will now be replaced with ___proto___ in parse

README.md
There's now a shields.io badge for .nycrc config files.
=> docs: there's now a coverage badge for .nycrc

package.json, test/yargs.js
Allow the use of dashed values when using `-f=` or `--bar=` format with `array` or `nargs`.
Fix #1602
=>  fix(dependencies): upgrade yargs-parser to fix #1602 

lib/usage.js, test/yargs.js
To allow modifying its translation with `updateLocale`/`updateStrings`.
Fixes #1598
=> fix(usage): translate 'options' group only when displaying help

locales/ja.json
Fixed 3 issues of Japanese translation described in #1617
=> fix(i18n): Japanese translation phrasing

LICENSE
Helps license scanning tools like https://github.com/licensee/licensee
to successfully detect that this is an MIT licensed project.
Same copyright and license, just moved the text in the file around to make the 🤖s happier. 😁 
Cheers!
🎩
=> docs: license update for bots

docs/api.md
`.demand` and `.reset` have this “[DEPRECATED]” tag in their titles, so `.defaults` should too for consistency.
=> docs(api): mark the `.defaults` alias as deprecated more clearly

README.md, docs/api.md, docs/examples.md
Some Markdown code blocks were defined with three backticks (```` ``` ````) and others with four (````` ```` `````). Markdown doesn’t treat the code block any differently with four backticks, so there is no value to the inconsistency. I replaced uses of four backticks with three, as three backticks is the most commonly-used syntax.
=> docs: normalize code block formatting

.github/workflows/release-please.yml
eliminates the need for having a hosted service that backs our release-please logic.
=> build: switch to action for release-please

package.json
Reverts temporarily yargs/yargs#1656, as eslint v7 no longer supports node 8, which we did not drop yet.
fix: #1669
refs: 1755aec
=> revert(deps): update dependency eslint back to v6.8

package.json
Was exploring the package locally and noticed these: I believe the completion scripts have been removed into [`completion-templates.ts`](https://github.com/yargs/yargs/blob/master/lib/completion-templates.ts), and am guessing that `build` use to be where the build output went?
It's good to remove them since makes the `package.json` a little smaller, but more importantly prevents publishing unneeded files.
fwiw `LICENSE` & `index.js` can actually be removed too as npm always included `README`, `CHANGELOG`, `LICENCE` and whatever `main` points at.
=> chore: remove old entries from `files` field in `package.json

docs/api.md, lib/yargs.ts, test/usage.js
add function to add multiple examples at once
#1683
=> feat(): add examples

.github/release-please.yml, .github/workflows/ci.yaml, README.md, package.json, test/yargs.js, yargs.js
Drops support for end of life Node 8.
Notes:
* `yargs@15.4.0` was released a few days ago, which includes much of @mleguen's work migrating to TypeScript (_we should be mindful that we might need to port a few fixes back to this release line._).
* we should not release `yargs@16.x.x` until we've finished the full TypeScript conversion, this includes @QmarkC's work on yargs-parser.
=> feat!: drop support for EOL Node 8

lib/yargs.ts, package.json, yargs.d.ts
1st part of 5th step of #1586: this PR ships a yargs.d.ts adapted from the one in `@types/yargs`.
=> chore(ts): ship yargs.d.ts

lib/usage.ts, test/usage.js, test/yargs.js
Display short switches first in usage,
and indent long switches only options.
Fix #1403
=> feat(usage): single char aliases first in help

README.md, browser.mjs, deno.ts, docs/browser.md, example/yargs.html, helpers.mjs, index.cjs, index.mjs, lib/utils/process-argv.ts, package.json, test/deno/yargs.test.ts, test/esm/yargs-test.mjs, types.ts
based on initial feedback regarding the `v16.x.x` API surface, this PR:
1. switches ESM and Deno entry points to export the `yargs` function as a default export.
2. moves deno's types into `./types.ts`.
3. adds a `helpers.mjs` with a `hidBin` helper, which replaces the verbose `getProcessArgvWithoutBin` helper.
TODO:
=> feat!: tweaks to API surface based on user feedback

lib/platform-shims/deno.ts, lib/platform-shims/esm.mjs, package.json
y18n has now been ported to ESM/Deno.
See: https://github.com/yargs/yargs/issues/1706
=> feat: i18n for ESM and Deno

helpers.mjs, index.cjs, lib/cjs.ts, lib/platform-shims/esm.mjs, package.json, test/esm/helpers.mjs, test/esm/yargs-test.mjs, test/helpers.cjs, yargs.cjs, yargs.js
@boneskull asked whether it was okay to use `applyExtends` as  a helper in `mocha`. I feel this is fine, but wanted to be more explicit about the helpers that yargs exports. Here's what's currently supported for both  ESM and  CJS:
* Parser:  the yargs-parser instance.
* applyExtends: helper for supporting `extends` behavior in config.
BREAKING CHANGE: rebase helper (which was just path.resolve) is no longer exposed.
=> feat(helpers): rebase, Parser, applyExtends now blessed helpers

docs/api.md, lib/validation.ts, lib/yargs-factory.ts, package.json, test/validation.cjs
Adds strictOptions() as a partner to strictCommands()
Fixes #1701
=> feat: adds strictOptions()

lib/platform-shims/cjs.ts, test/command.cjs, test/helpers/utils.cjs
=> fix: code was not passed to process.exit

lib/typings/common-types.ts, lib/usage.ts, lib/validation.ts, package.json
By shipping types in yargs-parser, we were breaking `@types/yargs` which relies on `@types/yargs-parser`.
For now let's avoid shipping types in both libraries.
=> fix(typescript): yargs-parser was breaking @types/yargs

lib/command.ts, lib/platform-shims/deno.ts, lib/typings/yargs-parser-types.ts, lib/yargs-factory.ts, package.json, test/deno/yargs.test.ts, test/esm/yargs-test.mjs, test/yargs.cjs
This moves the coercion of positional values to numbers to a post processing step, so that we can turn off this behavior during the first pass of parsing before we consume positionals.
Related work in yargs-parser: https://github.com/yargs/yargs-parser/pull/321
Fixes #1758
=> fix(positional): positional strings no longer drop decimals

docs/api.md
Closes #1760 
This argument was added in #1559 / `yargs@15.2.0`.
---
First contribution to this project so let me know if I need any additional changes in this PR!
=> docs: add deprecate to documentation

README.md, docs/api.md, docs/browser.md, docs/bundling.md
Webpack does not play nicely with dual mode ESM/CJS modules, this documents the steps necessary to bundle yargs as of 16.x.
Fixes #1754
=> docs: document how to bundle yargs with webpack/ncc

test/argsert.cjs, test/before.cjs
In test, throw on warnings so that we catch argsert issues.
Fixes #1666
=> test: throw on warning when in tests

docs/advanced.md, docs/api.md
onFinishCommand was not documented in api docs.
Fixes #1658, #1344
=> docs: document onFinishCommand option

deno.ts, types.ts
In version 1.4 Deno adopted;
- the tsconfig setting [importsNotUsedAsValues](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues) - https://github.com/denoland/deno/pull/7413
- the tsconfig setting [isolatedModules](https://www.typescriptlang.org/tsconfig#isolatedModules) when using the deno `--unstable` flag - https://github.com/denoland/deno/issues/7326 ([intended to be enabled by default in 1.5](https://github.com/denoland/deno/issues/7326))
These require the use of;
- type only imports for values which are only used as types (`importsNotUsedAsValues`)
- type only exports for types which are re-exported (`isolatedModules`)
I've added more details at https://github.com/yargs/yargs/issues/1771.
related prs:
- yargs-parser https://github.com/yargs/yargs-parser/pull/329
- y18n …
=> fix(deno): update types for deno ^1.4.0

README.md, deno.ts, lib/platform-shims/deno.ts, lib/yargs-factory.ts, test/deno/yargs.test.ts, types.ts
This gets yargs working again on deno@1.5.x, by dropping the complex `YargsInstance`.
Unfortunately `deno@1.5.x` seems to break the already fragile path handling logic that was being used to target both Node.js and Deno simultaneously. I'm not sure what the best path forward is, we might want to simply maintain our own type definitions for deno?
Refs https://github.com/yargs/yargs/pull/1792
Fixes https://github.com/yargs/yargs/issues/1794
CC: @ffMathy @KhushrajRathod
=> fix(deno): get yargs working on deno@1.5.x

docs/api.md
Middleware can be applied either before or after validation. When combined with a default command this allows you to perform a transformation after choices has already been enforced (as requested in #756)
Fixes #756
=> docs: add example of using middleware with choices

package.json
The reason for this change is explained in #1817.
TL;DR: yargs uses the `package.json`::`exports` field to define importable paths from the outside. Any files that are not explicitly listed in it cannot be required anymore. However, some tools may attempt to `require(node_modules/yargs/package.json)` to read package info and fail. This PR exposes the package.json file to the public.
=> chore: add package.json to module exports

docs/advanced.md, lib/command.ts, lib/yargs-factory.ts, test/command.cjs, test/deno/yargs.test.ts, test/esm/fixtures/commands/a.mjs, test/esm/fixtures/commands/b.mjs, test/esm/fixtures/commands/index.mjs, test/esm/fixtures/commands/subcommands/c.mjs, test/esm/fixtures/commands/subcommands/d.mjs, test/esm/fixtures/commands/subcommands/index.mjs, test/esm/yargs-test.mjs
.command() now accepts an array of modules, the intention being that this
makes it easier for people to build a complex hierarchical CLI in
environments that can not use requireDirectory().
=> feat: command() now accepts an array of modules

docs/api.md, docs/tricks.md
This updates the docs to help cover some of the issues discussed in #963.
I also copied the sample `parserConfiguration` usage from advanced.md#customizing-yargs-parser; it seems helpful to have an example in the API section, too.
=> Add descriptions of parsing numbers

.github/workflows/ci.yaml, docs/advanced.md, docs/api.md, lib/command.ts, lib/completion.ts, lib/usage.ts, lib/yargs-factory.ts, package.json, test/command.cjs, test/completion.cjs, test/middleware.cjs, test/usage.cjs, test/yargs.cjs
In `node@15` [top level await](https://v8.dev/features/top-level-await) is now supported 🎉. 
This means that we can have yargs return a promise in more situations, with users writing code that looks like this:
```js
import yargs from './index.mjs';
import { setTimeout } from 'timers/promises';
const argv = await yargs(process.argv.slice(2))
.command(
'foo',
'foo commnd',
() => {},
async (argv) => {
console.info('second')
await setTimeout(1000)
}
)
.middleware(async (argv) => {
console.info('first')
await setTimeout(1000)
argv.value = 99
}).argv;
console.info('third', argv)
```
This PR begins work to add better first class support of promises to yargs.
---
TODO:
BREAKING CHANGES:
* now returns a promise if handler is `async`.
* onFinishCommand removed, in favor of being able to await …
=> feat!: improve support for async/await

lib/completion-templates.ts
I manage [an AUR package](https://aur.archlinux.org/packages/readability-cli/#news) for my own node CLI tool, so I want to be able to install Bash/Zsh completions system-wide.
Bash completion works fine when I put it in `/usr/share/bash-completion/completions/<app name>`. But when I try to put the Zsh completion into `/usr/share/zsh/site-functions/_<app name>` it does not work at all.
This is fixed by adding `#compdef _<app name>` at the top of the completion file.
=> Zsh completion is now installable system-wide

lib/command.ts, test/yargs.cjs
Prior to this fix, we only cached the help message for commands
when using async commands. I believe we always want to cache the
help message for cases like #1853.
Fixes #1853
=> fix: always cache help message when running commands

lib/command.ts, lib/middleware.ts, lib/usage.ts, lib/validation.ts, lib/yargs-factory.ts, test/middleware.cjs, test/validation.cjs
1. global middleware will now be applied when no command is configured.
2. async middleware now works when used before validation.
BREAKING CHANGE: changes to middleware behavior:
* validation now applied after async middleware completes when applyBeforeValidation=true
* global middleware now applied when no command is configured
Refs: #1823
Fixes: #1351
=> feat(middleware)!: middleware improvements

lib/completion.ts, test/completion.cjs
See #1013 
Based on work by @tkarls (https://github.com/yargs/yargs/issues/1013#issuecomment-346814408). This is my first time working with TypeScript so my solution might be a bit ugly.
One thing that worries me is that this API requires you to use callbacks. There is no good way to overload this function:
```ts
export type CompletionFunction =
| SyncCompletionFunction
| AsyncCompletionFunction
| FallbackCompletionFunction;
interface SyncCompletionFunction {
(current: string, argv: Arguments): string[] | Promise<string[]>;
}
interface AsyncCompletionFunction {
(current: string, argv: Arguments, done: (completions: string[]) => any): any;
}
interface FallbackCompletionFunction {
(
current: string,
argv: Arguments,
defaultCompletion: () => any,
done: (completions: string[]) => any
): any; …
```
=> Allow calling standard completion function from custom one

lib/completion.ts, test/completion.cjs
When using default completion both `positional` and `option` arguments are treated the same. This results in completion suggesting `positional` arguments in an `option` form, which is incorrect:
```ts
yargs
.command(
'exec <pos-a> <pos-b>',
'Execute command.',
(yargs) => {
return yargs
.positional('pos-a', { type: 'string', desc: 'Pos A' })
.positional('pos-b', { type: 'string', desc: 'Pos B' })
.option({
'opt-a': { type: 'boolean', alias: 'oa', desc: 'Option A' },
'opt-b': { type: 'string', requiresArg: true, desc: 'Option B' },
});
},
)
.completion('completion', 'Completion.').argv;
```
```
$ ./index.js exec --
--help     -- Show help
--opt-a    -- Option A
--opt-b    -- Option B
--pos-a    -- Pos A
--pos-b    -- Pos B
--version  -- Show version number
```
```
$ ./index.js exec --pos-a …
```
=> feat: allow to access output of default completion in custom completion

README.md
Should reflect solution of this issue: https://github.com/yargs/yargs/issues/1450  
This seems to be correct in [the deno example](https://github.com/yargs/yargs#deno):  
```ts
...
yargs(Deno.args)
.command('download <files...>', 'download a list of files', (yargs: any) => {
return yargs.positional('files', {
describe: 'a list of files to do something with'
})
...
```
/cc @garyking
Please Let me know if I can improve this PR somehow.
=> docs(usage): add return to fix TS inheritance

lib/platform-shims/deno.ts
Fix: https://github.com/yargs/yargs/issues/1841#issuecomment-804770453
Not sure if this is a bug in deno itself, but for now this doesn't work when building distributable binaries. 
There is a distinction between the names of an exported value between  `deno run`  and `deno compile` when importing an object and using it as a key in a new object
In `'https://deno.land/x/yargs_parser@v20.2.4-deno/deno.ts'`
```ts
export default yargsParser
``` 
In `'https://deno.land/x/yargs/deno.ts'`
```ts
import Parser from 'https://deno.land/x/yargs_parser@v20.2.4-deno/deno.ts';
const newObject = {
Parser
}
``` 
This will create `{yargParser: Parser}` in `deno compile` while work as intended with `deno run`  where you get `{Parser: Parser}`
The codebase relies on `shim.Parser` and that will be `undefined` …
=> Use actual names for keys instead of inferring.

docs/advanced.md, docs/api.md, lib/command.ts, lib/completion.ts, lib/yargs-factory.ts, test/command.cjs, test/helpers/utils.cjs, test/middleware.cjs, test/usage.cjs, test/yargs.cjs
Fixes: https://github.com/yargs/yargs/issues/1042
BREAKING CHANGE: providing an async builder will now cause yargs to return async result
BREAKING CHANGE: .positional() now allowed at root level of yargs.
=>  feat: adds support for async builder

lib/yargs-factory.ts, test/command.cjs, test/middleware.cjs, test/yargs.cjs
If a callback is provided to `parse()` it will now be executed after all promises have resolved.
The cause of #1888, was that `this[kUnfreeze]();` was being called too soon, which set `this.#parseFn` to `null`.
Fixes #1888
=> fix(async): don't call parse callback until async ops complete

docs/api.md, lib/yargs-factory.ts, test/yargs.cjs
Introduces parseSync/parseAsync, allowing an application to explicitly state whether or not it expects the parse goal of yargs to be asynchronous or synchronous.
Refs: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52169
=> feat: add parseSync/parseAsync method

package.json, rollup.config.cjs
By minifying the CJS bundle we reduce the published size of yargs from 345 kB down to 264.9 kB. I'm comfortable making this trade off, given that (if it introduces any issues) we can push users towards ESM (which is not minified).
=> build(publishing): use terser to minify CJS code

deno.ts, test/deno/yargs.test.ts
Update deno entrypoint, and add test demonstrating `parseAsync()`.
=> test(deno): add example of parseAsync behavior

docs/api.md
When `fn` returns a string or error, it will cause .check() to fail. This was not documented. Adding it to docs for clarity.
Close: #1883
=> docs: clarify .check() behavior

lib/completion-templates.ts
fix https://github.com/yargs/yargs/issues/874
=> fix: completion script name clashing on bash

lib/yargs-factory.ts, test/yargs.cjs
The trick we were using of .alias("foo", "foo") to "tell" yargs-parser about a key
using coerce has a bug such that help output is broken. We can instead use
.key (https://github.com/yargs/yargs-parser/blob/master/lib/yargs-parser.ts#L191) which
is designed for exactly our purposes (telling yargs-parser a key exists, without
setting attributes such as description).
Fixes #1909
=> fix(coerce): options using coerce now displayed in help

lib/command.ts, lib/yargs-factory.ts, package.json, test/usage.cjs, test/yargs.cjs
The builder for default commands was not being properly applied when `.showHelp()` and `.getHelp()` were used.
Fixes #1912
=> fix(builder): apply default builder for showHelp/getHelp

package.json
see yargs/yargs-parser#363
and yargs/yargs-parser#350 for explanation
=> fix(deps): explicitly bump yargs-parser

lib/command.ts, lib/yargs-factory.ts, test/command.cjs, test/usage.cjs
Addresses two bugs with async builders:
1. if no arguments were provided to `.parse()`, results were not being awaited before unfreezing yargs instance.
2. `runCommand` was not awaiting async builders before returning results.
Fixes #1917
=> fix(builder): nested builder is now awaited

lib/cjs.ts, lib/command.ts, lib/middleware.ts, lib/platform-shims/deno.ts, lib/typings/common-types.ts, lib/utils/maybe-async-result.ts, lib/validation.ts
While looking through the repo, I saw a few lines/sections that could be simplified. 
This is my first OSS PR, so let me know if there are things I can do better.
I'll be looking through more of the repo, and eventually the issues tab, but if there is anything you want me to focus on, let me know!
=> refactor: small simplifications

docs/typescript.md
- Added section for config
Technically `moduleResolution` and `strict` aren't needed for the examples shown, but I thought they would be good touches.
- [main] Added explanation for the union typing when calling `.argv` or `.parse`, and how to fix it.  
- Added title for the typing of `choices()`
- Stated the typescript config used
---
Should close #1953
=> Better Typescript Documentation

lib/validation.ts, test/validation.cjs
Addresses: https://github.com/yargs/yargs/issues/1861
As always, let me know if I need to change/add/fix anything.
This should fail:
```js
const argv = yargs.strict().parse('foo');
console.log(argv) // { _: [ 'foo' ], '$0': 'example.js' }
```
Neither `unknownArguments` nor `unknownCommands` catch extra args when `commandKeys.length` is 0.
I added a block to check if there are any elements in `argv` that aren't in `currentContext.commands`. I made sure to tolerate args when `yargs.demand(number)`  is called, when the number of args falls within the min/max range.
This shouldn't fail:
```js
const argv = yargs.strict().demand(1).parse('foo');
console.log(argv) // { _: [ 'foo' ], '$0': 'example.js' }
```
I don't understand the `demand` logic well (as it's deprecated and not in the docs), so …
=> fix: strict should fail unknown arguments

lib/command.ts, lib/middleware.ts, lib/yargs-factory.ts, test/command.cjs
Addresses: https://github.com/yargs/yargs/issues/1966 and https://github.com/yargs/yargs/issues/1802
I know that the coerce middleware is being applied twice.
I ran the below example. I logged the execution of the functions that use `applyMiddleware`, and I logged the type/value of the arg during coercion.
```js
const argv = yargs("rule add foo bar baz")
.command("rule", "rule desc", (yargs) =>
yargs.command("add <name> <abc...>", "add desc", (yargs) =>
yargs.positional("abc", {
type: "string",
coerce: (arg) => console.log({ argType: typeof arg, arg }) || arg.join(" "),
})
)
).argv;
```
Logs look like this:
```
parse called
kRunYargsParserAndExecuteCommands called
runCommand called
parseAndUpdateUsage called
kRunYargsParserAndExecuteCommands called
runCommand called
parseAndUpdateUsage …
```
=> fix: coerce middleware should be applied once

lib/validation.ts, test/validation.cjs
This is an attemps at fixing #1091 and #1203.
The documentation for `implies` is:
> Given the key x is set, it is required that the key y is set.
But this check fails when the value of the key `y` is `0`, `false`, or empty string.
When `y` value is `false`, we might want `implies` to continue failing though. I'd like to have your input on that, and I will adjust that PR accordingly.
The issue came from `keyExists` which, instead of always returning a boolean, could returned the value of the key. That value is later on used like so:
```
if (key && !value) {
implyFail.push(` ${origKey} -> ${origValue}`);
}
```
Thus, that `if` resolved to `true` when `value` was `0`, `false` or `""`.
Having `keyExists` always returning a boolean seems more robust. I used `Object.hasOwnProperty` to check for …
=> fix: implies should not fail when implied key's value is 0, false or empty string

lib/command.ts, lib/yargs-factory.ts, test/command.cjs
Addresses: https://github.com/yargs/yargs/issues/1637
When executing the default command, if both positionals and options are provided under the same namespace, positionals will overwrite the options in argv. This doesn't happen if a command is provided.
This will behave correctly. `argv.foods` will have both `apples` and `carrots`
```js
yargs
.command({
command: "cmd [foods..]",
desc: "cmd desc",
builder: (yargs) =>
yargs.positional("foods", {
desc: "foods desc",
type: "string",
}),
handler: (argv) => {
console.log(argv);
},
})
.help()
.parse("cmd --foods apples carrots");
```
logs
```
// first time through parser (kRunYargsParserAndExecuteCommands)
{ args: 'cmd --foods apples carrots', config: { 'populate--': true } }
{ 'parsed.argv': { _: [ 'cmd', 'carrots' ], foods: 'apples' } }
// …
```
=> fix: positionals should not overwrite options

.github/workflows/ci.yaml
denolib/setup-deno is deprecated. CI passed in my fork.
=> fix: update deno CI action

lib/command.ts, test/command.cjs
- https://github.com/yargs/yargs/pull/1992
- https://github.com/mdn/browser-compat-data/pull/11990
Positional array defaults were getting combined with, instead of overwritten by, the provided values.
=> fix: positional array defaults should not be combined with provided values

lib/usage.ts
When settings the scriptName to an empty string, the help command will add an unnecessary whitespace before commands, and wrap the command usage string 1 character too early. This PR fixes this.
=> fix: help command spacing when scriptName is empty

lib/argsert.ts, lib/completion.ts, lib/utils/maybe-async-result.ts, test/completion.cjs
Hi!
This PR introduces support for auto completing choices if an option has been specified which has choices but no value has been selected yet. For example:
```
> cdktf convert --language <TAB>
csharp      java        python      typescript
```
when the option has been specified like this: ([source](https://github.com/hashicorp/terraform-cdk/blob/168349149773a969d64063a38d3a69a6d75680cb/packages/cdktf-cli/bin/cmds/convert.ts#L42-L45))
```typescript
.option("language", {
choices: ["typescript", "python", "csharp", "java"],
default: "typescript",
})
```
We use `yargs` for the [CDK for Terraform](https://github.com/hashicorp/terraform-cdk) and wanted to [introduce support for shell completion](https://github.com/hashicorp/terraform-cdk/issues/676). As we wanted to offer support for auto …
=> feat: autocomplete choices for options

lib/platform-shims/browser.mjs, lib/platform-shims/cjs.ts, lib/platform-shims/deno.ts, lib/platform-shims/esm.mjs, lib/typings/common-types.ts, lib/yargs-factory.ts, test/helpers/utils.cjs, test/usage.cjs
Addresses: #1979 and #1864
"version" can be passed as a key to `yargs.option()`, but this messes up parsing. 
The `yargs.version()` method already occupies that namespace.
This code
```js
yargs.command(
"cmd1",
"cmd1 desc",
(yargs) =>
yargs.option("version", {
alias: "v",
describe: "version desc",
type: "string",
}),
(argv) => {
console.log({ argv });
}
).parse('cmd1 --version 0.25.10')
```
produces this result:
```js
{
argv: {
_: [ 'cmd1', '0.25.10' ],
version: false,
v: false,
'$0': 'my-script.js'
}
}
```
I added a check in `yargs.option` that will ~throw an error~ emit a warning if an option (or its alias) is "version", unless they disabled version with `yargs.version(false)`.
=> fix: prevent version name collision

docs/api.md, example/nested.js
Addresses #1897
Let me know if you want me to change anything or add examples (i.e., subcommands).
=> docs: only use parse and argv at top level

docs/typescript.md
Hi all and thanks for making Yargs :-)
I believe that this:
```ts
const difficulties = ["normal", "nightmare", "hell"] as const;
type Difficulty = typeof difficulties[number];
```
gives the same result than:
```ts
type Difficulty = 'normal' | 'nightmare' | 'hell';
const difficulties: ReadonlyArray<Difficulty> = ['normal', 'nightmare', 'hell'];
```
but is better as it doesn't include twice the content of the list, and prevents missing elements (indeed, the following is valid despite the fact that one element is missing: `const difficulties: ReadonlyArray<Difficulty> = ['normal', 'hell'];`).
=> docs: improve typing of `Difficulty` in TypeScript example

example/bool.js, example/default_hash.js, example/divide.js, example/help.js, example/implies.js, example/implies_hash.js, example/requires_arg.js, example/strict.js, example/usage-options.js
- Remove unused var
- Add shebang
- Change short to alias
- Fix https://github.com/yargs/yargs/issues/1974
=> docs: modernize sample code

lib/yargs-factory.ts, test/validation.cjs
Addresses: https://github.com/yargs/yargs/issues/1694
When defining an option with `yargs.option`, this line is called:
```js
this.#options.key[key] = true;
```
This affects the behavior in`validation > unknownArguments > isValidAndSomeAliasIsNotNew`. Without the tracking of set keys, `unknownArguments` will fail (as described in the issue).
I turned that line into a reusable function so that `yargs.option` and the array/boolean/count/number/string methods have consistent behavior when using `yargs.strict`
=> fix: boolean option should work with strict

README.md
=> fix(docs): stop advertising .argv property

package.json
Update string-width to 4.2.3
In order to patch vulnerability [CVE-2021-3807](https://vuln.whitesourcesoftware.com/vulnerability/CVE-2021-3807), a downstream dependency has to be updated.
This dependency tree is:
yargs
string-width
strip-ansi
ansi-regex
The vulnerability for this CVE related to ansi-regex has been fixed in strip-ansi 6.0.1 which is used by string-width 4.2.3.
=> deps(security): CVE-2021-3807

lib/completion-templates.ts
If you do not generate a completion entry, use the default bash completion. If that also does not return a completion, fall back to "readline" default filename completion.
This allows you to complete on for example environment variables. `mycommand --option $OPT<tab>` would complete to `mycommand --option $OPTION` if there was an environment variable called `OPTION` set.
=> feat: fallback to default bash completion

.github/workflows/ci.yaml, lib/middleware.ts, package.json, rollup.config.cjs
I'm running into a few issues when running `build:cjs`:
- It looks like the ts logic for `Promise.all` has changed. I made a change to address this. (I used [this solution](https://github.com/microsoft/TypeScript/issues/46651#issuecomment-958599609))
- `@wessberg/rollup-plugin-ts` is throwing an error
```
TypeError: Cannot read properties of undefined (reading 'text')
at getExportedSymbolFromExportSpecifier (/.../yargs/node_modules/@wessberg/rollup-plugin-ts/src/service/transformer/declaration-bundler/util/create-export-specifier-from-name-and-modifiers.ts:49:35)
```
You can see a reproduction of the issue [here](https://github.com/yargs/yargs/runs/4316963468?check_suite_focus=true#step:5:34)
The issue is in [this line](https://github.com/wessberg/rollup-plugin-ts/blob/master/src/service/t …
=> build: fix ts build errors

lib/platform-shims/esm.mjs
For usage like:
- built final project used in a javascript vm
- project built on unix via webpack and used on windows (path format are incompatible with drive letters on windows)
https://github.com/webpack/webpack/issues/14445
=> fix: don't fail if "fileURLToPath(import.meta.url)" throws

lib/yargs-factory.ts, test/validation.cjs
Addresses: 
https://github.com/yargs/yargs/issues/2069
Check callback `options` is undefined. It should be an object.
The [docs](http://yargs.js.org/docs/#api-reference-checkfn-globaltrue) show `options` in the call signature for the callback in`check`. In [yargs 17](https://github.com/yargs/yargs/blob/main/lib/yargs-factory.ts#L296), options is missing from that call signature.
- Not sure if the options object I used is the correct one (or if it's in the correct state). 
- Not sure if mutable access to options should be exposed. Should it be read-only or a copy?
Let me know if there are any changes that need to happen, or if I should add more tests.
=> fix: re-add options to check callback

locales/ko.json
adapted following rules
boolean: '불리언' (ko wikipedia common)
default: '기본값'
argument: '인수' (parameter: '인자, 매개변수')
choices: '선택지'
given: '주어진'
missing: '주어지지 않은'  (the oppsite of given)
unknown: '알 수 없는'
invalid: '유효하지 않은'
version number: '버전'
mutually exclusive: '동시제 지정할 수 없-'
+ Added appropriate postpositions
Translating "deprecated" and "deprecated: %s" is out of my consideration as I couldn't describe them as no short sentences.
=> fix(translations): correct Korean translation

README.md
[`DefinitelyTyped/DefinitelyTyped`](https://github.com/DefinitelyTyped/DefinitelyTyped)'s default branch is `master`. The `main` branch does not exist.
=> docs: correct @types/yargs URL in readme

lib/completion.ts, test/completion.cjs
This is an improvement on #2018. Changes:
- Improvement: Completion for choices will now work for all possible aliases of an option and not just the default long option. This is accomplished by iterating over all known aliases of the provided option, and checking for `choices` on each.
- Fix: changed the RegExp used to remove hypens (`-`), because it removed ALL hyphens from the argument, which broke options like `--long-option-with-dashes`. It now only removes dashes at the beginning of the option.
- Fix: changed the check for option arguments to match options that begin with `'-'`, instead of `'--'`, to include short options
=> multiple: improved completion for choices

docs/api.md
- Link would 404 on the website
=> docs: "default command" link in `.positional`

lib/command.ts, lib/usage.ts, test/usage.cjs
Addresses: 
https://github.com/yargs/yargs/issues/2030
https://github.com/yargs/yargs/issues/2102
The usage from a failed default command is missing the following:
- argument descriptions
- optional arguments
- possibly more (?)
In the code and output below, you will see that the failed default command is missing descriptions and optional arguments. (I omitted the command usage output, as it's not part of the issue.)
```js
yargs('')
.command({
command: '$0 <arg1>',
desc: 'default desc',
builder: yargs => yargs
.option('arg1', {
type: 'string',
desc: 'arg1 desc (default command)',
demandOption: true
})
.option('arg2', {
type: 'string',
desc: 'arg2 desc (default command)'
}),
handler: argv => {
console.log(argv)
}
})
.command({
command: 'cmd1 <arg1>',
desc: 'cmd1 desc',
builder: yargs => …
```
=> fix: failed command usage string is missing arg descriptions and optional args

docs/examples.md
I've been looking for how to use [inquirer](https://github.com/SBoudrias/Inquirer.js/) with yargs,
and found this issue: https://github.com/yargs/yargs/issues/1476 
So here is how I use an async command to prompt things with inquirer
cheers
=> added an example using inquirer prompting

lib/completion.ts, test/completion.cjs
=> fix: hide hidden options from completion

example/yargs.html
Some browser don't support `code` so I added a fallback for `keyCode`
=> event.keyCode is deprecated, use new `.code` API

lib/typings/common-types.ts, lib/typings/yargs-parser-types.ts, lib/usage.ts, lib/yargs-factory.ts, test/usage.cjs
Addresses: https://github.com/yargs/yargs/issues/2085
When `showHelpOnFail` is used globally, it doesn't work. 
This is because `usage.reset()` sets failMessage to null.
I added a `globalFailMessage` variable to capture the global mesage.
On fail, `failMessage || globalFailMessage` is printed. I figured if both are provided, the more specific message should be shown.
I saw that `null | undefined` was used a lot, so I made type `nil`. (Idea borrowed from lodash isNil)
=> fix: Show message when showHelpOnFail is chained globally

lib/command.ts, lib/yargs-factory.ts, test/command.cjs
- https://github.com/yargs/yargs/issues/2130
- https://github.com/yargs/yargs/issues/2158
- https://github.com/yargs/yargs/issues/2159
- https://github.com/yargs/yargs/issues/2162
- coerce always runs, even if arg isn't provided
- coerce sets the value on argv, resulting in keys existing on argv that weren't passed.
- any validation around certain keys (not) existing on argv manifest unintended behavior
I'm fixing two coerce bugs:
- bug one: coerce and related argument not passed
- bug two: coerce and strip-aliased
Coerce doesn't behave correctly when the related arg is not passed. 
There are two unintentional side-effects:
- a new arg is set on argv
- coerce function is run
`coerce > maybeAsyncResult > resultHandler` sets argv, which shouldn't happen.
```js
const input = 'cmd1' …
```
=> fix: coerce pollutes argv

browser.d.ts, lib/yerror.ts, package.json
I'm attempting to use this in a browser environment and have run into a few issues.
=> Add browser.d.ts and check for existence of Error.captureStackTrace()

lib/completion.ts, test/completion.cjs
following code inside method `argsContainKey` in `completion.ts` have stopped working:
```
if (this.aliases) {
// search for aliases in parsed argv
// can't do the same thing for main option names because argv can contain default values
for (const alias of this.aliases[key]) {
if (argv[alias] !== undefined) return true;
```
Currently argv contains default value for aliases too, so I just look at args instead
Test included
=> fix(completion): support for default flags

package.json
Due to the `yargs.mjs` file not being published, the fix merged with #2151 is not effective yet. This change should fix that.
```
Cannot find module './node_modules/yargs/yargs.mjs' imported from ./cli.js
```
_Edit:_ Also added missing `browser.d.ts`
=> fix: add missing entries to published files

lib/platform-shims/esm.mjs
Fixes #2122.
In the case of ava, `mainFilename` changes like below way.
```js
// existing code's value:
mainFilename: /usr/local/lib/
// this PR's value:
mainFilename: /usr/local/lib/node_modules/ava/
```
This enable yargs to find ava's package.json properly.
=> fix: cannot find package.json on ESM

lib/command.ts, lib/yargs-factory.ts, test/command.cjs
Relates to: 
issue: https://github.com/yargs/yargs/issues/2096
PR: https://github.com/yargs/yargs/pull/1992
PR: https://github.com/yargs/yargs/pull/2006
There were a few problems with pull 1992:
- Positional arguments combined with defaults (solved by 2006)
- Positional arguments combined with config objects (solved by this PR)
- Not accounting for kebab case arguments (solved by this PR)
- Are there any other sources of values that I'm not accounting for? (I would rather not have another follow up PR for a third source 🤦 )
- Is there a better way to write the logic? It works, but I can't help but think there's a more elegant solution.
=> fix: passed arguments should take precedence over values in config

lib/yargs-factory.ts, test/yargs.cjs
Addresses: https://github.com/yargs/yargs/issues/2178
locale and kGuessLocale can enter an infinite loop
There's regex logic that turns '.UTF-8' into '', and downstream there is logic checking if that value is falsey (instead of undefined).
As a result, kGuessLocale and locale call each other infinitely.
```js
this.locale(locale.replace(/[.:].*/, ''))
```
This line is what converts `'.UTF-8'` into `''`. I don't know if my fix is sufficient or if the real problem is here.
=> fix: prevent infinite loop with locale

locales/ru.json
Resolves #2180.
I’ll put my thoughts here so you can correct me.
```json
"Arguments %s and %s are mutually exclusive": "Аргументы %s и %s являются взаимоисключающими",
```
The translation is verified, see the [English](https://manpages.ubuntu.com/manpages/impish/en/man8/restorecon.8.html) (“`-p` and `-v` options are mutually exclusive”) and [Russian](https://manpages.ubuntu.com/manpages/impish/ru/man8/restorecon.8.html) (“параметры `-p` и `-v` являются взаимоисключающими”) Ubuntu man pages.
```json
"Positionals:": "Позиционные аргументы:",
```
There is no proper translation for the word “positionals”. That’s why the translation contains the noun (“Позиционные аргументы” means “Positional arguments”).
```json
"deprecated": "устарела",
"deprecated: %s": "устарела: %s"
```
The word …
=> fix(lang): add missing terms to Russian translation

lib/command.ts, lib/yargs-factory.ts
Relates to: https://github.com/yargs/yargs/pull/2161#discussion_r847542318
=> refactor: use prototype

lib/command.ts, test/middleware.cjs
Addresses: https://github.com/yargs/yargs/issues/2124
The result of `applyMiddleware` is `Arguments | Promise<Arguments>`, but the code treats it synchronously. Whenever it returns a promise, that promise isn't handled as such.
This problem is easier to spot when `strict` is used
```js
const input = 'cmd1 -f Hello -b world'
yargs(input)
.command(
'cmd1',
'cmd1 desc',
yargs => yargs
.option('foo', { type: 'string', alias: 'f', required: true })
.option('bar', { type: 'string', alias: 'b', required: true })
.middleware(async argv => {
console.log('sleeping')
await new Promise(r => setTimeout(r, 2000))
console.log('waking up')
return argv
}, true),
argv => {
console.log(argv)
})
.strict()
.parse()
```
I put a console log after `applyMiddleware` is called, and I could see that 'waking up' …
=> Fix async middleware

lib/completion-templates.ts
Replace reference to `~/.zsh_profile` with the correct `~/.zprofile`. [Source](https://stackoverflow.com/questions/23090390/is-there-anything-in-zsh-like-bash-profile)
=> fix(completion): correct zsh installation instructions

lib/usage.ts, test/usage.cjs
Resolves https://github.com/yargs/yargs/issues/2200
I had to modify the test `should wrap based on window-size if no wrap is provided` because the actual length of the non-wrapped output is `5` and not `4`. 👍
=> feat(usage): add YARGS_DISABLE_WRAP env variable to disable wrap

lib/yargs-factory.ts, test/usage.cjs
Fixes #2169
My original patch from #2169 broke some existing tests, due to it being necessary to call `this.describe` when initially setting up an option even if no explicit description is set.
So this PR implements this behavior by only calling `this.describe` if there is no existing description OR if the new description is a string.
I added a test that I confirmed fails on main and passes in this PR.
=> fix: dont clobber description for multiple option calls

lib/typings/common-types.ts
This PR fixes https://github.com/yargs/yargs/issues/2236, by following the suggestion of the Typescript compiler.
=> fix(typescript): address warning with objectKeys

locales/cs.json
Removing an extra comma at the end of the line.
=> fix(lang): fix "Not enough non-option arguments" message for the Czech language

lib/platform-shims/deno.ts
Fix for Deno UI/UX prompt issue described in #2216.
=> fix(deno): refactor to avoid prompts during module import (#2216)

.github/workflows/ci.yaml, .github/workflows/release-please.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> build: GitHub Workflows security hardening

package.json
Currently `yargs` is not usable in Deno when using`.env()` because `Deno.env.toObject()` is not returned, causing a fatal error.
This was fixed in https://github.com/yargs/yargs-parser/pull/432 and released in yargs-parser v21.0.1.
This dependency bump will fix `.env` in `yargs` for Deno users.
=> fix(deps): update dependency yargs-parser to v21.1.1

locales/fi.json
Fixed a typo in the singular unknown argument message (argumenttn -> argumentti).
=> fix(lang): typo in Finnish unknown argument singular form

lib/usage.ts, lib/yargs-factory.ts, test/usage.cjs
Addresses: https://github.com/yargs/yargs/issues/2153
Given the following:
```js
yargs('cmd1 --help')
.command(
'cmd1',
'cmd1 desc',
yargs => yargs
.option('opt1', {
type: 'string',
choices: ['foo', 'bar', 'baz'],
alias: 'o',
required: true,
description: "A long description that might break formatting"
}),
argv => console.log(argv)
)
.hideOptionExtras()
.strict()
.parse()
```
The `hideOptionExtras` would cause the following output
```
cmd1 desc
Options:
--help     Show help                                             [boolean]
--version  Show version number                                   [boolean]
-o, --opt1     A long description that might break formatting
[string] [required] [choices: "foo", "bar", "baz"]
```
to look like this instead
```
cmd1 desc
Options:
--help     Show help …
```
=> feature: add method to hide option extras

locales/en.json
Adds the unknown command strings to the `en` locale. This has no affect on the output, since they are the same as in the code! The intent is so people updating or creating other locales can see the strings available for localising.
Placing the strings after unknown argument in the same place as in the `fr` locale from #1560, which looks a good place.
Closes: #2259
=> chore: add en strings for unknown command

lib/completion.ts, test/completion.cjs
This PR fixes https://github.com/yargs/yargs/issues/2268.  
I find the original option for the alias and copy its description to the alias.
As a result, the option and its alias are collected together and aligned in the completion.
=> fix: copy the description of the option to its alias in completion

lib/command.ts, test/usage.cjs
freeze() was not being called prior to reset(), resulting in display issues for default sub-commands.
Fixes #2291
CC: @Tobbe, @bglimepoint
=> fix: address display bug with default sub-commands

lib/completion.ts, test/completion.cjs
Current completion crashes when using ZSH and having negable options.
```
[error] TypeError: Cannot read properties of undefined (reading 'find')
at D.completeOptionKey (//node_modules/yargs/build/index.cjs:1255:20)
at //node_modules/yargs/build/index.cjs:1191:37
at Array.forEach (<anonymous>)
at D.optionCompletions (//node_modules/yargs/build/index.cjs:1184:26)
at D.defaultCompletion (//node_modules/yargs/build/index.cjs:1158:12)
at n (//node_modules/yargs/build/index.cjs:1313:23)
at D.getCompletion (//node_modules/yargs/build/index.cjs:1314:31)
at te.[runYargsParserAndExecuteCommands] (//node_modules/yargs/build/index.cjs:3161:27)
at _.parseAndUpdateUsage (//node_modules/yargs/build/index.cjs:426:8)
at _.applyBuilderUpdateUsageAndParse (//node_modules/yargs/build/index.cjs:412:17)
```
=>     fix: do not crash completion when having negable options

package.json
Inspired by work in #2281, add an npm run-script for "watch".
Both `tsc` and `rollup` support watch.
=> Add watch run-script

docs/api.md
The first example of [`.coerce(key, fn)`](https://yargs.js.org/docs/#api-reference-coercekey-fn) is invalid: an `await` is used in a non-`async` function.
```js
var argv = require('yargs/yargs')(process.argv.slice(2))
.coerce('file', function (arg) {
return await require('fs').promises.readFile(arg, 'utf8')
})
.argv
```
=> docs: Fix example of coerce

lib/yargs-factory.ts, test/yargs.cjs
Relates to #2307 and #2161. Yargs does the coerce separately after yargs-parser, and should both apply the coerce values to the aliases and camel-case variations, but also not add them back if the parser configuration said not to include them in the results. 
Use the fact that yargs-parser has already decided what variations belong in the results, and update just the naming variations already present in the results.
Fixes #2307, fixes #2311
=> fix: coerce should play well with parser configuration

docs/api.md
A Typescript error was reported which was due to a missing return in a builder function for a `.usage()` call based on the example code. I did not do a deep dive into whether the TypeScript was correct, but the main builder function example has a return so it seemed pretty likely the return is expected for usage too.
Closes: #2321
=> docs: missing return in usage builder function

docs/typescript.md
Simple fix, prompted by investigation for #2381
=> docs: fix typos in .terminalWidth example

docs/api.md, locales/he.json
=> feat(locale): added hebrew translation

.nycrc, lib/platform-shims/cjs.ts, package.json, rollup.config.cjs, tsconfig.json
This addresses bit rot in the rollup compilation, which is used to expose both a CJS and MJS module.
Now that you can require ESM modules in CJS, I think there's an argument for making yargs pure ESM, which would remove the need for this build step, and would reduce the size of yargs by 100%, see:
https://nodejs.org/api/modules.html#loading-ecmascript-modules-using-require
=> fix(build): address problems with typescript compilation

docs/browser.md, lib/command.ts, lib/platform-shims/browser.mjs, lib/platform-shims/deno.ts, lib/platform-shims/esm.mjs, lib/typings/common-types.ts, lib/utils/apply-extends.ts
The shim files abstract Node specific logic away from Deno and browser entry points. I had drifted away form using shims when implementing the addDirectory logic.
=> fix(browser): fix shims so that yargs continues working in browser context

lib/command.ts, test/command.mjs
The issue context is under https://github.com/yargs/yargs/pull/2451/files/9e920df512e869d3d5f7917f9dbd79f99b26b93c#diff-3378419d97c7d3aa5e4c5a36f8744505164ed98aeda47707e070f8df8496b91f
The main problem is that the commandDir API function no longer supports the absolute commands directory, which was supported previously. @shadowspawn suggested changing from path.join to path.resolve. I tested his solution and it worked. Therefore, I've created this pull request.
BTW, I ran the `npm run test` with all the passes. but `npm run test:esm` with failed "throws an error if commndDir() used in ESM mode" I think it will not be a test case in yargs@next
=> fix: addDirectory do not support absolute command dir

lib/yargs-factory.ts, test/completion.mjs
There is an incompatibility between the parser configuration options and the completion feature within yargs. Setting strip-dashed: true in the parser configuration causes the completion feature to fail.
This is because the completion feature relies on passing '--get-yargs-completions' verbatim to yargs. Within the [Completion class](https://github.com/yargs/yargs/blob/main/lib/completion.ts?rgh-link-date=2023-05-08T17%3A03%3A24Z), the completionKey is explicitly set to get-yargs-completions. Within the YargsInstance, we explicitly check the following condition: completionKey in argv, in this location: [main/lib/yargs-factory.ts#L2054](https://github.com/yargs/yargs/blob/main/lib/yargs-factory.ts?rgh-link-date=2023-05-08T17%3A03%3A24Z#L2054)
Since the argv has been parsed already at this …
=> fix: parser-configuration should work well with generated completion script

lib/yargs-factory.ts
When using `bunx --bun package-name`, it claims bun is the cli name. However this incorrect, so this PR changes the behavior to work like node!
the --bun isn't strictly necessarily as if you don't have bun installed, then it force attempts to use bun runtime by changing the path.
(note, I have indeed tested this behavior and it works)
fixes #2377
=> fix(yargs-parser): support bun for getting cli name

locales/de.json
Changing de localization for 'count' to 'Anzahl' because 'Zähler' is closer to 'counter'
=> Fix 'count' for de locale
