index.js
=> default should be obj not array, see #51

.coveralls.yml, README.md
updated the badges now that Alex has transferred the GitHub repo.
=> updated the badges

README.md
Consistent visual style with the other badges, different color though.
=> Tweak NPM version badge

index.js, lib/parser.js, test/parser.js, test/yargs.js
=> fix for camel-case alias bug

index.js, test/yargs.js
Every key you specify with yargs will now have a placeholder in `argv`.
=> set placeholders for all keys see #115

index.js, test/parser.js, test/usage.js, test/yargs.js
see #114, there was a bug involving the yargs singleton which was causing parsing inconsistencies.
=> found parsing inconsistencies between yargs([]) and yargs.parse([])

lib/validation.js, test/usage.js, test/validation.js
=> validation/demand: fail without message if msg is null

lib/parser.js, test/fixtures/settings.js, test/parser.js
Let me know what you think. I need this for code42day/postcss-cli#5 - but it did turn out a bit more complicated than what I imagined.
=> add support for config specified in .js files

lib/usage.js, test/usage.js
pretty serialization of arrays and objects, see #132
=> nicer serialization of object and array default values see #132

.travis.yml, lib/usage.js, lib/validation.js, test/usage.js
=> make .requiresArg() work with .string()

README.md
To make things a bit more readable, I've updated some of te the [metasyntactic variables](http://en.wikipedia.org/wiki/Metasyntactic_variable) in the README file to names that may make it a bit easier to understand.
=> Readme: update with more useful-looking examples

index.js
see: https://github.com/bcoe/yargs/issues/138
=> also detect iojs bin

index.js, lib/completion.js, lib/parser.js, lib/usage.js, lib/validation.js, package.json, test/completion.js, test/fixtures/bin.js, test/fixtures/settings.js, test/helpers/utils.js, test/integration.js, test/parser.js, test/usage.js, test/validation.js, test/yargs.js
Since our coding style was almost there any ways, I've decided to move yargs to @feross' standard style.
This addresses the code-style question brought up in #144, and I hope will make it easier for people to make contributions.
=> updating codebase to use @feross' standard

index.js, test/usage.js
merge of: https://github.com/bcoe/yargs/pull/146
=> merged @nylen's dollar-zero fix with the standard coding style that was pulled in

README.md, index.js, test/parser.js
Hey,
this PR adds a description the config option so it will be displayed in the help/usage message.
=> config option in help messages

index.js, lib/completion.js, lib/parser.js, lib/usage.js, lib/validation.js, package.json, test/completion.js, test/helpers/utils.js, test/parser.js, test/usage.js, test/validation.js, test/yargs.js
Upgrading a few outdated dependencies, had to make a few changes for new `standard` rules.
=> upgrading outdated dependencies

index.js, test/parser.js
=> slight spelling nit

.travis.yml
Gives builds a faster startup time.
ref http://docs.travis-ci.com/user/workers/container-based-infrastructure/
=> Travis CI container build

README.md
fix merge conflict with https://github.com/bcoe/yargs/pull/216
=> sort methods alphabetically in readme

README.md, locales/pt.json
Just an updated version of [PR 224](https://github.com/bcoe/yargs/pull/224) with merge conflicts resolved (and up to date with master).
Thanks to @codemonkey3045 for the translation!
=> Portuguese locale (conflict resolved)

.travis.yml, test/usage.js, test/yargs.js
Good sleuthing @nexdrew, I've emailed travis and multiple os support should now be enabled:
https://github.com/bcoe/yargs/commit/b5ceb3303a70890d0e546de3386f7ca9accd23e7#commitcomment-12968428
=> multiple os should now work

package.json
bumped verison of cliui to address https://github.com/nexdrew/yargonaut/issues/7
=> bumped version of cliui

README.md, locales/pt-BR.json
Just added the locale pt-BR (Portuguese Brazil).
Obrigado
=> Added the locale pt-BR (Portuguese Brazil).

README.md, locales/nb.json
https://simple.wikipedia.org/wiki/Bokm%C3%A5l
=> Add Norwegian Bokmål locale

README.md, locales/id.json
=> Add Indonesian translation

CHANGELOG.md
=> update the 4.x changelog

lib/parser.js, test/parser.js
=> alias should be applied to camel-case form of argument

contributing.md
* added a contributor code of conduct, care of http://contributor-covenant.org/
* added a brief list of instructions to help folks get started with contributions.
=> added contributor code of conduct, and contribution guidelines

package.json
'cause I want to be able to run `npm docs yargs` and get the shiny new website
=> Put the yargs homepage in its package data

README.md, index.js, lib/usage.js, package.json, test/usage.js, test/yargs.js
I swear this is the last time :dancers:
This PR requires the following before merging:
=> add number type opts

locales/tr.json
Related to https://github.com/yargs/yargs/issues/404
=> Added Turkish number translation

locales/ko.json
=> Add "number" translation for Korean

locales/es.json
=> Add "number" to es.json

locales/ja.json
=> Add number translation to ja.json

locales/id.json
=> Add "number" translation for Indonesian

locales/it.json
Add translation for Italian.
Signed-off-by: madrisan <davide.madrisan@gmail.com>
=> Add translation for Italian

index.js
thanks @elas7 \o/
If you have a few minutes, try `npm i yargs@next` I want to make sure I haven't broken anything with this refactor.
=> remove duplicate line from index.js

index.js, test/usage.js
=> remove duplicated export rebase from index.js

CHANGELOG.md, package.json, test/usage.js
lots of great work from @elas7 \o/
=> updating CHANGELOG.md in prep for release

README.md, package.json, test/integration.js
* replace win-spawn with cross-spawn-async.
* upgrade to yargs-parser with fancy new features.
* upgrade to smaller cliui.
* fix badge in README.
=> upgrade various dependencies

README.md
As added in yargs-parser 2.4.0
=> docs(environment): document nested options in environment variables

README.md, example/xup.js
Sorry for the bad pun.
I hate making a pull request for something this small, but I think it's the general consensus to put the closing brace and the 'else' on the same line.
=> Arrrrrr....n't you going to use good coding standards in the examples?

package.json
=> chore(package): update nyc to version 6.4.1

lib/blocking-io.js, lib/usage.js, package.json, test/fixtures/issue-497.js, test/integration.js, yargs.js
=> fix: make stdout flush on newer versions of Node.js

package.json, test/fixtures/issue-497.js
=> fix: fake a tty in tests, so that we can use the new set-blocking

lib/command.js, test/command.js
=> feat: providing a builder for commands is now optional

lib/validation.js, test/fixtures/package.json, test/validation.js, yargs.js
This will eventually fix #547 
This PR is still a WIP as the new added test passes regardless of whether `boolean-negation` is turned on or off, however, I'd love to hear what folks think about the general approach already.
=> add config lookup for .implies()

README.md, package.json
BREAKING CHANGE: coerce is now applied as a final step after other parsing is complete
CC: @maxrimue
=> chore: upgrade yargs-parser

locales/pl.json
Per https://github.com/yargs/yargs/issues/649
=> Polish translations for 'did you mean' and 'aliases'

locales/ja.json
=> Japanese translations for 'did you mean' and 'aliases' 

locales/id.json
=> Indonesian translations for 'did you mean' and 'aliases'

locales/es.json
=> Spanish translation for "aliases" and "did you mean %s?"

locales/ru.json
Thsi is a locale file with Russian translations as discussed in #649.
=> Russian locale file

locales/tr.json
=> feat: Turkish translations for 'did you mean' and 'aliases'

locales/hu.json
#649  Hey
I added the Hungarian translations for the project
=> Hungarian translation added

locales/pt_BR.json
Address brazilian portuguese translations for `aliases:` and `Did you mean %s?`
=> Add pt_BR translations to #649

README.md, locales/th.json
I added a Thai translation locale file, `th.json`, as discussed in #649.
=> Add Thai locale file

README.md
Thanks to our many contributors, yargs now has 4 new languages to add to its supported locales list!
=> docs: add new languages to supported locales

locales/nl.json
Created a Dutch translation of en.json, according to issue #649 
Happy Hacktoberfest!
=> Created nl.json

locales/be.json
=> Added Belarusian translation

locales/ru.json
=> Fix Russian translation

package.json
@ssonal this upgrades us to the `next` release of `yargs-parser`, which introduces your support for #598, #617. Go ahead and take it for a spin 👍
=> feat: update to yargs-parser that addresses #598, #617

README.md
I just noticed this was breaking https at https://www.npmjs.com/package/yargs
https://i.imgur.com/4WFGVJ9.png
=> Use https for image URL at README.md

package.json
1. adds extra config addressing #688.
2. fixes #716
=> feat: pull in new version of yargs-parser

test/yargs.js, yargs.js
fixes https://github.com/yargs/yargs/issues/735
=> Fix [object Object] property on describe with object

yargs.js
Bugfix -> https://github.com/yargs/yargs/issues/827
=> fix(*): fix demandOption ignores false value

lib/command.js, test/command.js, yargs.js
BREAKING CHANGE: commands will now not be executed if they are proceeded by another positional argument
fixes: #853 
CC: @gajus
=> fix: commands are now applied in order, from left to right

test/yargs.js, yargs.js
=> fix: help now takes precedence over command recommendation

README.md
switching to slack for community conversations.
=> docs: add link to community slack

docs/api.md, lib/validation.js, test/validation.js, yargs.js
Fixes #921 and fixes #845 
`npm test` passes, but I haven't tried to run yargs with the changes, nor added any new tests (sorry).
I've also not updated the docs.
=> Allow implies and conflicts to accept array values

lib/validation.js, test/validation.js
Regarding https://github.com/yargs/yargs/pull/922#issuecomment-329473901
=> fix: implications fails only displayed once

lib/usage.js, test/usage.js
=> feat: multiple usage calls are now collected, not replaced

README.md
show off the new `.positional()` method.
=> docs: switch to using .positional() in example

locales/ko.json
seems commit log has specific pattern now but i don't know how to write commit log about translation.
=> #976 add ko translation

locales/pt_BR.json
Update the translation with the new ones.
=> Add pt-BR translation to #976

locales/pl.json
Ref: https://github.com/yargs/yargs/pull/976
=> feat(translation): Update pl-PL translations

completion.sh.hbs, lib/completion.js, test/completion.js, yargs.js
=> fix: use correct completion command in generated completion script

locales/hi.json
This fixes #976 for the locale: HI (Hindi).
=> Chore: new translations for API overhaul for locale: HI (Hindi)

lib/command.js
=> fix: tiny spacing issue with usage

package.json
=> chore: explicitly update dependencies

test/command.js
@zenflow went ahead and added a test for the happy path 👍
=> chore: add test for happy path of async command handler

yargs.js
Patch to resolve #1031 : Add `dirname` sanity check on `findUp`
=> Patch to #1031 : Add `dirname` sanity check on `findUp` 

docs/advanced.md
This PR fixes the docs for middlware
=> fix middlware docs

lib/validation.js, test/validation.js
fixes #1041 
CC: @TheLarkInn, @shellscape, @jddxf
=> fix: requiresArg should only be enforced if argument exists

README.md
Got the logo and title to the top with center alignment and restructured the contents a bit. Let me know if you guys have any suggestions. Thanks!
=> restructured the contents of readme

docs/api.md
Add some useful documentation for when using array() with positional()
=> Add documentation for array()

test/completion.js, yargs.js
=> fix(completion): Avoid default command and recommendations during completion

docs/api.md, test/usage.js, yargs.js
=> feat: Allow setting scriptName $0

.gitignore, lib/validation.js, locales/pirate.json, test/validation.js
=> fix: translation not working when using __ with a single parameter

lib/middleware.js, test/middleware.js
=> Fix type check in the .middleware() method

docs/advanced.md
Add some documentation around how to best test command modules. I found this information in different parts of the docs and thought it might be helpful to consolidate it to a small guide alongside the command module.
=> docs: testing command modules

test/middleware.js
=> test: add tests for alias behavior, based on conversations today

lib/argsert.js, lib/command.js, lib/usage.js, package.json, test/argsert.js, test/completion.js, test/fixtures/configured-bin.js, test/middleware.js, test/usage.js, test/validation.js, test/yargs.js, yargs.js
addresses security vulnerability with handlebars. update to new standard nits.
=> chore: update deps

completion.zsh.hbs, lib/completion.js, package.json, test/completion.js
collapses together @aorinevo and @trevorlinton's work, supersedes:
https://github.com/yargs/yargs/pull/1299
https://github.com/yargs/yargs/pull/1297
=> chore: collapse together Aori and Trevor's work

docs/api.md
=> doc: clarify parserConfiguration object structure

README.md, docs/tricks.md
=> docs: add section on dashes in string arguments

example/usage-options.js
=> fix(docs): usage-options example 

docs/api.md
Feels silly to open such a tiny PR, but I noticed this while reading the docs and my OCD was stronger than me :sweat_smile: 
Great docs btw! :+1:
=> fix(docs): broken markdown link

lib/validation.js
refactor code to a more concise version.
=> chore: Minor refactor

.travis.yml, lib/command.js, package.json, test/yargs.js, yargs.js
now that we're able to hit 100% line coverage with c8 (this took some upstream fixes in v8), I'm switching yargs over to the c8 project I've been working on.
=> build: switch to c8 for coverage

test/parser.js, yargs.js
=> feat: Expose `Parser` from `require('yargs/yargs')`

CHANGELOG.md, package.json, test/yargs.js, yargs.js
see: https://github.com/babel/babel/pull/10733
=> fix: addresses bug caused by delete being called on frozen object

docs/advanced.md
=> Update advance.md: it's -> its

package.json
=> chore(deps): upgrade decamelize and get rid of @types/decamelize

docs/advanced.md
Added syntax highlighting to code blocks in the advanced docs.
=> docs: add missing syntax highlighting

lib/validation.ts, test/validation.js
=> Revert "fix(strictCommands): report unknown argument instead of unknown comma…"

lib/command.ts, lib/yargs.ts
=> fix(yargs): add missing command(module) signature

.github/publish.yml, .github/workflows/ci.yaml, .github/workflows/release-please.yml
switch to latest release-please for both publication and tagging.
=> build: use release-please action

lib/validation.ts, test/validation.cjs
@cspotcode this should return things to the old behavior.
Fixes #1732
=> fix: make positionals in -- count towards validation

package.json
Refs: https://github.com/yargs/yargs/issues/1756
=> fix(modules): module path was incorrect

docs/advanced.md, docs/api.md
=> docs(terminology): update terminology

package.json
See https://github.com/yargs/yargs/pull/1776, https://github.com/yargs/yargs-parser/pull/333, https://github.com/yargs/cliui/pull/91, https://github.com/lukeed/escalade/pull/6
=> chore(deps): update `cliui`, `escalade`, `y18n`, `yargs-parser`

package.json
As requested. This PR updates standardx from version 5.0.0 to version 7.0.0.
=> chore(deps): update standardx

.eslintignore, lib/platform-shims/browser.mjs, package.json, test/command.cjs, test/completion.cjs, test/deno/platform-shim.test.ts, test/deno/yargs.test.ts, test/esm/fixtures/commands/a.mjs, test/esm/fixtures/commands/subcommands/c.mjs, test/esm/fixtures/commands/subcommands/d.mjs, test/fixtures/bin.js, test/fixtures/cmddir/deep/deeper/deeper_still/limbo.js, test/fixtures/cmddir/deep/deeper/inception.js, test/fixtures/cmddir/deep/within-a-dream.js, test/fixtures/cmddir/dream.js, test/fixtures/cmddir_cyclic/cyclic.js, test/fixtures/cmddir_noname/nameless.js, test/fixtures/command-module.js, test/fixtures/command.js, test/fixtures/issue-497.js, test/fixtures/no-require-main.js, test/fixtures/normal-bin.js, test/fixtures/opt-assignment-and-positional-command-arg.js, test/fixtures/symlink-bin.js, test/middleware.cjs, test/usage.cjs, test/validation.cjs, test/yargs.cjs
Using `gts` in conjunction with `standardx` was buggy (outputting a variety of warnings I couldn't figure out how to address).
This moves us to using `gts` and `eslint` which is pulled in by `gts`.
=> test: simplify/fix linting

lib/yargs-factory.ts
=> Added commands function (similar to options function)

docs/bundling.md
Adds updated docs for webpack.
CC: @iansu
=> docs(webpack): add updated docs on webpack

renovate.json
keep string-width pinned for the time being.
=> build: ignore string-width

README.md
Document `hideBin` in top level README.md.
Fixes #1871
=> docs: document hideBin

lib/cjs.ts
Forgot to update min version to 12.
Refs: #1933
=> fix(build): Node 12 is now minimum version

lib/command.ts, lib/completion.ts, lib/typings/yargs-parser-types.ts, lib/usage.ts, lib/utils/set-blocking.ts, lib/yargs-factory.ts, test/command.cjs, test/helpers/utils.cjs, test/middleware.cjs, test/usage.cjs, test/yargs.cjs
No worries if you can't get to this soon, I know you're busy.
=> refactor: use modern array helpers, etc.

docs/api.md, locales/uz.json
Issue: Locales Translate to Uzbek #1960
=> feat(locales): Added Uzbek translation

docs/bundling.md
=> docs: add esbuild bundling guide

docs/api.md
Also see DefinitelyTyped/DefinitelyTyped#59062
=> Fix hyphenation typo in API documentation

.github/workflows/ci.yaml, .github/workflows/release-please.yml
=> Revert "chore: Set permissions for GitHub actions"

test/usage.cjs
=> test: remove console.log

locales/cs.json
=> feat(lang): Czech locale

lib/platform-shims/deno.ts
Minor PR which implements the fix described in #2186.
=> fix(deno): use 'globalThis' instead of 'window' (#2186)

lib/typings/common-types.ts, package.json
=> fix(deps): cliui with forced strip-ansi update

CHANGELOG.md, lib/yargs-factory.ts, package.json
=> fix: exit after async handler done
